// Code generated by Fern. DO NOT EDIT.

package client

import (
	agentapi "github.com/AIEngineering26/promptvm-go-sdk/agentapi"
	apikeys "github.com/AIEngineering26/promptvm-go-sdk/apikeys"
	authentication "github.com/AIEngineering26/promptvm-go-sdk/authentication"
	billing "github.com/AIEngineering26/promptvm-go-sdk/billing"
	cliauth "github.com/AIEngineering26/promptvm-go-sdk/cliauth"
	collections "github.com/AIEngineering26/promptvm-go-sdk/collections"
	contexts "github.com/AIEngineering26/promptvm-go-sdk/contexts"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	directories "github.com/AIEngineering26/promptvm-go-sdk/directories"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	marketplacebrowse "github.com/AIEngineering26/promptvm-go-sdk/marketplacebrowse"
	marketplacecomments "github.com/AIEngineering26/promptvm-go-sdk/marketplacecomments"
	marketplacecreator "github.com/AIEngineering26/promptvm-go-sdk/marketplacecreator"
	marketplacecreatordashboard "github.com/AIEngineering26/promptvm-go-sdk/marketplacecreatordashboard"
	marketplacelistings "github.com/AIEngineering26/promptvm-go-sdk/marketplacelistings"
	marketplaceratings "github.com/AIEngineering26/promptvm-go-sdk/marketplaceratings"
	marketplaceskillsfeed "github.com/AIEngineering26/promptvm-go-sdk/marketplaceskillsfeed"
	marketplacesocial "github.com/AIEngineering26/promptvm-go-sdk/marketplacesocial"
	marketplacesubscriptions "github.com/AIEngineering26/promptvm-go-sdk/marketplacesubscriptions"
	mcp "github.com/AIEngineering26/promptvm-go-sdk/mcp"
	onboarding "github.com/AIEngineering26/promptvm-go-sdk/onboarding"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
	organizations "github.com/AIEngineering26/promptvm-go-sdk/organizations"
	promptdeployments "github.com/AIEngineering26/promptvm-go-sdk/promptdeployments"
	promptexport "github.com/AIEngineering26/promptvm-go-sdk/promptexport"
	promptorganization "github.com/AIEngineering26/promptvm-go-sdk/promptorganization"
	promptresolution "github.com/AIEngineering26/promptvm-go-sdk/promptresolution"
	prompts "github.com/AIEngineering26/promptvm-go-sdk/prompts"
	promptversions "github.com/AIEngineering26/promptvm-go-sdk/promptversions"
	resources "github.com/AIEngineering26/promptvm-go-sdk/resources"
	search "github.com/AIEngineering26/promptvm-go-sdk/search"
	sharing "github.com/AIEngineering26/promptvm-go-sdk/sharing"
	skills "github.com/AIEngineering26/promptvm-go-sdk/skills"
	skillspublic "github.com/AIEngineering26/promptvm-go-sdk/skillspublic"
	templates "github.com/AIEngineering26/promptvm-go-sdk/templates"
	workspaces "github.com/AIEngineering26/promptvm-go-sdk/workspaces"
)

type Client struct {
	Authentication              *authentication.Client
	CliAuth                     *cliauth.Client
	Billing                     *billing.Client
	AgentAPI                    *agentapi.Client
	SkillsPublic                *skillspublic.Client
	Contexts                    *contexts.Client
	MarketplaceSkillsFeed       *marketplaceskillsfeed.Client
	Sharing                     *sharing.Client
	APIKeys                     *apikeys.Client
	Onboarding                  *onboarding.Client
	Organizations               *organizations.Client
	MarketplaceSocial           *marketplacesocial.Client
	MarketplaceCreator          *marketplacecreator.Client
	MarketplaceBrowse           *marketplacebrowse.Client
	MarketplaceListings         *marketplacelistings.Client
	MarketplaceCreatorDashboard *marketplacecreatordashboard.Client
	MarketplaceSubscriptions    *marketplacesubscriptions.Client
	MarketplaceRatings          *marketplaceratings.Client
	MarketplaceComments         *marketplacecomments.Client
	Prompts                     *prompts.Client
	PromptVersions              *promptversions.Client
	PromptDeployments           *promptdeployments.Client
	PromptResolution            *promptresolution.Client
	Collections                 *collections.Client
	Templates                   *templates.Client
	PromptOrganization          *promptorganization.Client
	PromptExport                *promptexport.Client
	Directories                 *directories.Client
	Resources                   *resources.Client
	Skills                      *skills.Client
	Workspaces                  *workspaces.Client
	Search                      *search.Client
	Mcp                         *mcp.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Authentication:              authentication.NewClient(options),
		CliAuth:                     cliauth.NewClient(options),
		Billing:                     billing.NewClient(options),
		AgentAPI:                    agentapi.NewClient(options),
		SkillsPublic:                skillspublic.NewClient(options),
		Contexts:                    contexts.NewClient(options),
		MarketplaceSkillsFeed:       marketplaceskillsfeed.NewClient(options),
		Sharing:                     sharing.NewClient(options),
		APIKeys:                     apikeys.NewClient(options),
		Onboarding:                  onboarding.NewClient(options),
		Organizations:               organizations.NewClient(options),
		MarketplaceSocial:           marketplacesocial.NewClient(options),
		MarketplaceCreator:          marketplacecreator.NewClient(options),
		MarketplaceBrowse:           marketplacebrowse.NewClient(options),
		MarketplaceListings:         marketplacelistings.NewClient(options),
		MarketplaceCreatorDashboard: marketplacecreatordashboard.NewClient(options),
		MarketplaceSubscriptions:    marketplacesubscriptions.NewClient(options),
		MarketplaceRatings:          marketplaceratings.NewClient(options),
		MarketplaceComments:         marketplacecomments.NewClient(options),
		Prompts:                     prompts.NewClient(options),
		PromptVersions:              promptversions.NewClient(options),
		PromptDeployments:           promptdeployments.NewClient(options),
		PromptResolution:            promptresolution.NewClient(options),
		Collections:                 collections.NewClient(options),
		Templates:                   templates.NewClient(options),
		PromptOrganization:          promptorganization.NewClient(options),
		PromptExport:                promptexport.NewClient(options),
		Directories:                 directories.NewClient(options),
		Resources:                   resources.NewClient(options),
		Skills:                      skills.NewClient(options),
		Workspaces:                  workspaces.NewClient(options),
		Search:                      search.NewClient(options),
		Mcp:                         mcp.NewClient(options),
		options:                     options,
		baseURL:                     options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
