// Code generated by Fern. DO NOT EDIT.

package client

import (
	agentapi "sdk/agentapi"
	ai "sdk/ai"
	apikeys "sdk/apikeys"
	authentication "sdk/authentication"
	billing "sdk/billing"
	cliauth "sdk/cliauth"
	collections "sdk/collections"
	contexts "sdk/contexts"
	core "sdk/core"
	directories "sdk/directories"
	internal "sdk/internal"
	marketplacebrowse "sdk/marketplacebrowse"
	marketplacecomments "sdk/marketplacecomments"
	marketplacecreator "sdk/marketplacecreator"
	marketplacecreatordashboard "sdk/marketplacecreatordashboard"
	marketplacelistings "sdk/marketplacelistings"
	marketplaceratings "sdk/marketplaceratings"
	marketplaceskillsfeed "sdk/marketplaceskillsfeed"
	marketplacesocial "sdk/marketplacesocial"
	marketplacesubscriptions "sdk/marketplacesubscriptions"
	mcp "sdk/mcp"
	onboarding "sdk/onboarding"
	option "sdk/option"
	organizations "sdk/organizations"
	promptdeployments "sdk/promptdeployments"
	promptexport "sdk/promptexport"
	promptorganization "sdk/promptorganization"
	promptresolution "sdk/promptresolution"
	prompts "sdk/prompts"
	promptversions "sdk/promptversions"
	resources "sdk/resources"
	search "sdk/search"
	settings "sdk/settings"
	sharing "sdk/sharing"
	skills "sdk/skills"
	skillspublic "sdk/skillspublic"
	templates "sdk/templates"
	workspaces "sdk/workspaces"
)

type Client struct {
	Authentication              *authentication.Client
	CliAuth                     *cliauth.Client
	Billing                     *billing.Client
	AgentAPI                    *agentapi.Client
	SkillsPublic                *skillspublic.Client
	Contexts                    *contexts.Client
	MarketplaceSkillsFeed       *marketplaceskillsfeed.Client
	Sharing                     *sharing.Client
	APIKeys                     *apikeys.Client
	Onboarding                  *onboarding.Client
	Organizations               *organizations.Client
	MarketplaceSocial           *marketplacesocial.Client
	MarketplaceCreator          *marketplacecreator.Client
	MarketplaceBrowse           *marketplacebrowse.Client
	MarketplaceListings         *marketplacelistings.Client
	MarketplaceCreatorDashboard *marketplacecreatordashboard.Client
	MarketplaceSubscriptions    *marketplacesubscriptions.Client
	MarketplaceRatings          *marketplaceratings.Client
	MarketplaceComments         *marketplacecomments.Client
	Settings                    *settings.Client
	Prompts                     *prompts.Client
	PromptVersions              *promptversions.Client
	PromptDeployments           *promptdeployments.Client
	PromptResolution            *promptresolution.Client
	Collections                 *collections.Client
	Templates                   *templates.Client
	PromptOrganization          *promptorganization.Client
	PromptExport                *promptexport.Client
	Directories                 *directories.Client
	Resources                   *resources.Client
	Skills                      *skills.Client
	Workspaces                  *workspaces.Client
	Search                      *search.Client
	Ai                          *ai.Client
	Mcp                         *mcp.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Authentication:              authentication.NewClient(options),
		CliAuth:                     cliauth.NewClient(options),
		Billing:                     billing.NewClient(options),
		AgentAPI:                    agentapi.NewClient(options),
		SkillsPublic:                skillspublic.NewClient(options),
		Contexts:                    contexts.NewClient(options),
		MarketplaceSkillsFeed:       marketplaceskillsfeed.NewClient(options),
		Sharing:                     sharing.NewClient(options),
		APIKeys:                     apikeys.NewClient(options),
		Onboarding:                  onboarding.NewClient(options),
		Organizations:               organizations.NewClient(options),
		MarketplaceSocial:           marketplacesocial.NewClient(options),
		MarketplaceCreator:          marketplacecreator.NewClient(options),
		MarketplaceBrowse:           marketplacebrowse.NewClient(options),
		MarketplaceListings:         marketplacelistings.NewClient(options),
		MarketplaceCreatorDashboard: marketplacecreatordashboard.NewClient(options),
		MarketplaceSubscriptions:    marketplacesubscriptions.NewClient(options),
		MarketplaceRatings:          marketplaceratings.NewClient(options),
		MarketplaceComments:         marketplacecomments.NewClient(options),
		Settings:                    settings.NewClient(options),
		Prompts:                     prompts.NewClient(options),
		PromptVersions:              promptversions.NewClient(options),
		PromptDeployments:           promptdeployments.NewClient(options),
		PromptResolution:            promptresolution.NewClient(options),
		Collections:                 collections.NewClient(options),
		Templates:                   templates.NewClient(options),
		PromptOrganization:          promptorganization.NewClient(options),
		PromptExport:                promptexport.NewClient(options),
		Directories:                 directories.NewClient(options),
		Resources:                   resources.NewClient(options),
		Skills:                      skills.NewClient(options),
		Workspaces:                  workspaces.NewClient(options),
		Search:                      search.NewClient(options),
		Ai:                          ai.NewClient(options),
		Mcp:                         mcp.NewClient(options),
		options:                     options,
		baseURL:                     options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
