// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

// Kind catalogue
var (
	listContextKindsResponseFieldKinds              = big.NewInt(1 << 0)
	listContextKindsResponseFieldAgentSkillsVersion = big.NewInt(1 << 1)
)

type ListContextKindsResponse struct {
	Kinds              []*ListContextKindsResponseKindsItem `json:"kinds" url:"kinds"`
	AgentSkillsVersion string                               `json:"agent_skills_version" url:"agent_skills_version"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListContextKindsResponse) GetKinds() []*ListContextKindsResponseKindsItem {
	if l == nil {
		return nil
	}
	return l.Kinds
}

func (l *ListContextKindsResponse) GetAgentSkillsVersion() string {
	if l == nil {
		return ""
	}
	return l.AgentSkillsVersion
}

func (l *ListContextKindsResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListContextKindsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetKinds sets the Kinds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextKindsResponse) SetKinds(kinds []*ListContextKindsResponseKindsItem) {
	l.Kinds = kinds
	l.require(listContextKindsResponseFieldKinds)
}

// SetAgentSkillsVersion sets the AgentSkillsVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextKindsResponse) SetAgentSkillsVersion(agentSkillsVersion string) {
	l.AgentSkillsVersion = agentSkillsVersion
	l.require(listContextKindsResponseFieldAgentSkillsVersion)
}

func (l *ListContextKindsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListContextKindsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListContextKindsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListContextKindsResponse) MarshalJSON() ([]byte, error) {
	type embed ListContextKindsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListContextKindsResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listContextKindsResponseKindsItemFieldName            = big.NewInt(1 << 0)
	listContextKindsResponseKindsItemFieldDescription     = big.NewInt(1 << 1)
	listContextKindsResponseKindsItemFieldDefaultIsPublic = big.NewInt(1 << 2)
	listContextKindsResponseKindsItemFieldMetadataSchema  = big.NewInt(1 << 3)
	listContextKindsResponseKindsItemFieldContentSpec     = big.NewInt(1 << 4)
	listContextKindsResponseKindsItemFieldFileSpec        = big.NewInt(1 << 5)
)

type ListContextKindsResponseKindsItem struct {
	Name            ListContextKindsResponseKindsItemName `json:"name" url:"name"`
	Description     string                                `json:"description" url:"description"`
	DefaultIsPublic bool                                  `json:"defaultIsPublic" url:"defaultIsPublic"`
	MetadataSchema  map[string]interface{}                `json:"metadataSchema" url:"metadataSchema"`
	ContentSpec     map[string]interface{}                `json:"contentSpec" url:"contentSpec"`
	FileSpec        map[string]interface{}                `json:"fileSpec" url:"fileSpec"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListContextKindsResponseKindsItem) GetName() ListContextKindsResponseKindsItemName {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListContextKindsResponseKindsItem) GetDescription() string {
	if l == nil {
		return ""
	}
	return l.Description
}

func (l *ListContextKindsResponseKindsItem) GetDefaultIsPublic() bool {
	if l == nil {
		return false
	}
	return l.DefaultIsPublic
}

func (l *ListContextKindsResponseKindsItem) GetMetadataSchema() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.MetadataSchema
}

func (l *ListContextKindsResponseKindsItem) GetContentSpec() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.ContentSpec
}

func (l *ListContextKindsResponseKindsItem) GetFileSpec() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.FileSpec
}

func (l *ListContextKindsResponseKindsItem) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListContextKindsResponseKindsItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextKindsResponseKindsItem) SetName(name ListContextKindsResponseKindsItemName) {
	l.Name = name
	l.require(listContextKindsResponseKindsItemFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextKindsResponseKindsItem) SetDescription(description string) {
	l.Description = description
	l.require(listContextKindsResponseKindsItemFieldDescription)
}

// SetDefaultIsPublic sets the DefaultIsPublic field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextKindsResponseKindsItem) SetDefaultIsPublic(defaultIsPublic bool) {
	l.DefaultIsPublic = defaultIsPublic
	l.require(listContextKindsResponseKindsItemFieldDefaultIsPublic)
}

// SetMetadataSchema sets the MetadataSchema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextKindsResponseKindsItem) SetMetadataSchema(metadataSchema map[string]interface{}) {
	l.MetadataSchema = metadataSchema
	l.require(listContextKindsResponseKindsItemFieldMetadataSchema)
}

// SetContentSpec sets the ContentSpec field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextKindsResponseKindsItem) SetContentSpec(contentSpec map[string]interface{}) {
	l.ContentSpec = contentSpec
	l.require(listContextKindsResponseKindsItemFieldContentSpec)
}

// SetFileSpec sets the FileSpec field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListContextKindsResponseKindsItem) SetFileSpec(fileSpec map[string]interface{}) {
	l.FileSpec = fileSpec
	l.require(listContextKindsResponseKindsItemFieldFileSpec)
}

func (l *ListContextKindsResponseKindsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListContextKindsResponseKindsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListContextKindsResponseKindsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListContextKindsResponseKindsItem) MarshalJSON() ([]byte, error) {
	type embed ListContextKindsResponseKindsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListContextKindsResponseKindsItem) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type ListContextKindsResponseKindsItemName string

const (
	ListContextKindsResponseKindsItemNamePrompt ListContextKindsResponseKindsItemName = "prompt"
	ListContextKindsResponseKindsItemNameSkill  ListContextKindsResponseKindsItemName = "skill"
)

func NewListContextKindsResponseKindsItemNameFromString(s string) (ListContextKindsResponseKindsItemName, error) {
	switch s {
	case "prompt":
		return ListContextKindsResponseKindsItemNamePrompt, nil
	case "skill":
		return ListContextKindsResponseKindsItemNameSkill, nil
	}
	var t ListContextKindsResponseKindsItemName
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListContextKindsResponseKindsItemName) Ptr() *ListContextKindsResponseKindsItemName {
	return &l
}
