// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	big "math/big"
	time "time"
)

var (
	browseMarketplaceCreatorsRequestFieldQ     = big.NewInt(1 << 0)
	browseMarketplaceCreatorsRequestFieldSort  = big.NewInt(1 << 1)
	browseMarketplaceCreatorsRequestFieldPage  = big.NewInt(1 << 2)
	browseMarketplaceCreatorsRequestFieldLimit = big.NewInt(1 << 3)
)

type BrowseMarketplaceCreatorsRequest struct {
	Q     *string                               `json:"-" url:"q,omitempty"`
	Sort  *BrowseMarketplaceCreatorsRequestSort `json:"-" url:"sort,omitempty"`
	Page  *string                               `json:"-" url:"page,omitempty"`
	Limit *string                               `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BrowseMarketplaceCreatorsRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsRequest) SetQ(q *string) {
	b.Q = q
	b.require(browseMarketplaceCreatorsRequestFieldQ)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsRequest) SetSort(sort *BrowseMarketplaceCreatorsRequestSort) {
	b.Sort = sort
	b.require(browseMarketplaceCreatorsRequestFieldSort)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsRequest) SetPage(page *string) {
	b.Page = page
	b.require(browseMarketplaceCreatorsRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsRequest) SetLimit(limit *string) {
	b.Limit = limit
	b.require(browseMarketplaceCreatorsRequestFieldLimit)
}

var (
	createMarketplaceCreatorProfileRequestFieldBio         = big.NewInt(1 << 0)
	createMarketplaceCreatorProfileRequestFieldWebsite     = big.NewInt(1 << 1)
	createMarketplaceCreatorProfileRequestFieldSocialLinks = big.NewInt(1 << 2)
	createMarketplaceCreatorProfileRequestFieldAvatarURL   = big.NewInt(1 << 3)
	createMarketplaceCreatorProfileRequestFieldDisplayName = big.NewInt(1 << 4)
)

type CreateMarketplaceCreatorProfileRequest struct {
	Bio         string                 `json:"bio" url:"-"`
	Website     *string                `json:"website,omitempty" url:"-"`
	SocialLinks map[string]interface{} `json:"socialLinks,omitempty" url:"-"`
	AvatarURL   *string                `json:"avatarUrl,omitempty" url:"-"`
	DisplayName *string                `json:"displayName,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateMarketplaceCreatorProfileRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileRequest) SetBio(bio string) {
	c.Bio = bio
	c.require(createMarketplaceCreatorProfileRequestFieldBio)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileRequest) SetWebsite(website *string) {
	c.Website = website
	c.require(createMarketplaceCreatorProfileRequestFieldWebsite)
}

// SetSocialLinks sets the SocialLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileRequest) SetSocialLinks(socialLinks map[string]interface{}) {
	c.SocialLinks = socialLinks
	c.require(createMarketplaceCreatorProfileRequestFieldSocialLinks)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileRequest) SetAvatarURL(avatarURL *string) {
	c.AvatarURL = avatarURL
	c.require(createMarketplaceCreatorProfileRequestFieldAvatarURL)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileRequest) SetDisplayName(displayName *string) {
	c.DisplayName = displayName
	c.require(createMarketplaceCreatorProfileRequestFieldDisplayName)
}

var (
	getMarketplaceCreatorProfileRequestFieldUserID = big.NewInt(1 << 0)
)

type GetMarketplaceCreatorProfileRequest struct {
	UserID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetMarketplaceCreatorProfileRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileRequest) SetUserID(userID string) {
	g.UserID = userID
	g.require(getMarketplaceCreatorProfileRequestFieldUserID)
}

type BrowseMarketplaceCreatorsRequestSort string

const (
	BrowseMarketplaceCreatorsRequestSortTop       BrowseMarketplaceCreatorsRequestSort = "top"
	BrowseMarketplaceCreatorsRequestSortInstalls  BrowseMarketplaceCreatorsRequestSort = "installs"
	BrowseMarketplaceCreatorsRequestSortListings  BrowseMarketplaceCreatorsRequestSort = "listings"
	BrowseMarketplaceCreatorsRequestSortFollowers BrowseMarketplaceCreatorsRequestSort = "followers"
	BrowseMarketplaceCreatorsRequestSortNewest    BrowseMarketplaceCreatorsRequestSort = "newest"
)

func NewBrowseMarketplaceCreatorsRequestSortFromString(s string) (BrowseMarketplaceCreatorsRequestSort, error) {
	switch s {
	case "top":
		return BrowseMarketplaceCreatorsRequestSortTop, nil
	case "installs":
		return BrowseMarketplaceCreatorsRequestSortInstalls, nil
	case "listings":
		return BrowseMarketplaceCreatorsRequestSortListings, nil
	case "followers":
		return BrowseMarketplaceCreatorsRequestSortFollowers, nil
	case "newest":
		return BrowseMarketplaceCreatorsRequestSortNewest, nil
	}
	var t BrowseMarketplaceCreatorsRequestSort
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (b BrowseMarketplaceCreatorsRequestSort) Ptr() *BrowseMarketplaceCreatorsRequestSort {
	return &b
}

// Creators
var (
	browseMarketplaceCreatorsResponseFieldData = big.NewInt(1 << 0)
	browseMarketplaceCreatorsResponseFieldMeta = big.NewInt(1 << 1)
)

type BrowseMarketplaceCreatorsResponse struct {
	Data []*BrowseMarketplaceCreatorsResponseDataItem `json:"data" url:"data"`
	Meta *BrowseMarketplaceCreatorsResponseMeta       `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BrowseMarketplaceCreatorsResponse) GetData() []*BrowseMarketplaceCreatorsResponseDataItem {
	if b == nil {
		return nil
	}
	return b.Data
}

func (b *BrowseMarketplaceCreatorsResponse) GetMeta() *BrowseMarketplaceCreatorsResponseMeta {
	if b == nil {
		return nil
	}
	return b.Meta
}

func (b *BrowseMarketplaceCreatorsResponse) GetExtraProperties() map[string]interface{} {
	return b.extraProperties
}

func (b *BrowseMarketplaceCreatorsResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponse) SetData(data []*BrowseMarketplaceCreatorsResponseDataItem) {
	b.Data = data
	b.require(browseMarketplaceCreatorsResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponse) SetMeta(meta *BrowseMarketplaceCreatorsResponseMeta) {
	b.Meta = meta
	b.require(browseMarketplaceCreatorsResponseFieldMeta)
}

func (b *BrowseMarketplaceCreatorsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BrowseMarketplaceCreatorsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BrowseMarketplaceCreatorsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BrowseMarketplaceCreatorsResponse) MarshalJSON() ([]byte, error) {
	type embed BrowseMarketplaceCreatorsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BrowseMarketplaceCreatorsResponse) String() string {
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	browseMarketplaceCreatorsResponseDataItemFieldUserID        = big.NewInt(1 << 0)
	browseMarketplaceCreatorsResponseDataItemFieldDisplayName   = big.NewInt(1 << 1)
	browseMarketplaceCreatorsResponseDataItemFieldUsername      = big.NewInt(1 << 2)
	browseMarketplaceCreatorsResponseDataItemFieldAvatarURL     = big.NewInt(1 << 3)
	browseMarketplaceCreatorsResponseDataItemFieldIsVerified    = big.NewInt(1 << 4)
	browseMarketplaceCreatorsResponseDataItemFieldBio           = big.NewInt(1 << 5)
	browseMarketplaceCreatorsResponseDataItemFieldListingsCount = big.NewInt(1 << 6)
	browseMarketplaceCreatorsResponseDataItemFieldInstalls      = big.NewInt(1 << 7)
	browseMarketplaceCreatorsResponseDataItemFieldFollowers     = big.NewInt(1 << 8)
	browseMarketplaceCreatorsResponseDataItemFieldIsFollowing   = big.NewInt(1 << 9)
)

type BrowseMarketplaceCreatorsResponseDataItem struct {
	UserID        *string `json:"userId,omitempty" url:"userId,omitempty"`
	DisplayName   *string `json:"displayName,omitempty" url:"displayName,omitempty"`
	Username      *string `json:"username,omitempty" url:"username,omitempty"`
	AvatarURL     *string `json:"avatarUrl,omitempty" url:"avatarUrl,omitempty"`
	IsVerified    *bool   `json:"isVerified,omitempty" url:"isVerified,omitempty"`
	Bio           *string `json:"bio,omitempty" url:"bio,omitempty"`
	ListingsCount *int    `json:"listingsCount,omitempty" url:"listingsCount,omitempty"`
	Installs      *int    `json:"installs,omitempty" url:"installs,omitempty"`
	Followers     *int    `json:"followers,omitempty" url:"followers,omitempty"`
	IsFollowing   *bool   `json:"isFollowing,omitempty" url:"isFollowing,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetUserID() *string {
	if b == nil {
		return nil
	}
	return b.UserID
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetDisplayName() *string {
	if b == nil {
		return nil
	}
	return b.DisplayName
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetUsername() *string {
	if b == nil {
		return nil
	}
	return b.Username
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetAvatarURL() *string {
	if b == nil {
		return nil
	}
	return b.AvatarURL
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetIsVerified() *bool {
	if b == nil {
		return nil
	}
	return b.IsVerified
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetBio() *string {
	if b == nil {
		return nil
	}
	return b.Bio
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetListingsCount() *int {
	if b == nil {
		return nil
	}
	return b.ListingsCount
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetInstalls() *int {
	if b == nil {
		return nil
	}
	return b.Installs
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetFollowers() *int {
	if b == nil {
		return nil
	}
	return b.Followers
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetIsFollowing() *bool {
	if b == nil {
		return nil
	}
	return b.IsFollowing
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) GetExtraProperties() map[string]interface{} {
	return b.extraProperties
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetUserID(userID *string) {
	b.UserID = userID
	b.require(browseMarketplaceCreatorsResponseDataItemFieldUserID)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetDisplayName(displayName *string) {
	b.DisplayName = displayName
	b.require(browseMarketplaceCreatorsResponseDataItemFieldDisplayName)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetUsername(username *string) {
	b.Username = username
	b.require(browseMarketplaceCreatorsResponseDataItemFieldUsername)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetAvatarURL(avatarURL *string) {
	b.AvatarURL = avatarURL
	b.require(browseMarketplaceCreatorsResponseDataItemFieldAvatarURL)
}

// SetIsVerified sets the IsVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetIsVerified(isVerified *bool) {
	b.IsVerified = isVerified
	b.require(browseMarketplaceCreatorsResponseDataItemFieldIsVerified)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetBio(bio *string) {
	b.Bio = bio
	b.require(browseMarketplaceCreatorsResponseDataItemFieldBio)
}

// SetListingsCount sets the ListingsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetListingsCount(listingsCount *int) {
	b.ListingsCount = listingsCount
	b.require(browseMarketplaceCreatorsResponseDataItemFieldListingsCount)
}

// SetInstalls sets the Installs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetInstalls(installs *int) {
	b.Installs = installs
	b.require(browseMarketplaceCreatorsResponseDataItemFieldInstalls)
}

// SetFollowers sets the Followers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetFollowers(followers *int) {
	b.Followers = followers
	b.require(browseMarketplaceCreatorsResponseDataItemFieldFollowers)
}

// SetIsFollowing sets the IsFollowing field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseDataItem) SetIsFollowing(isFollowing *bool) {
	b.IsFollowing = isFollowing
	b.require(browseMarketplaceCreatorsResponseDataItemFieldIsFollowing)
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler BrowseMarketplaceCreatorsResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BrowseMarketplaceCreatorsResponseDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed BrowseMarketplaceCreatorsResponseDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BrowseMarketplaceCreatorsResponseDataItem) String() string {
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	browseMarketplaceCreatorsResponseMetaFieldPage  = big.NewInt(1 << 0)
	browseMarketplaceCreatorsResponseMetaFieldLimit = big.NewInt(1 << 1)
	browseMarketplaceCreatorsResponseMetaFieldTotal = big.NewInt(1 << 2)
)

type BrowseMarketplaceCreatorsResponseMeta struct {
	Page  int `json:"page" url:"page"`
	Limit int `json:"limit" url:"limit"`
	Total int `json:"total" url:"total"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BrowseMarketplaceCreatorsResponseMeta) GetPage() int {
	if b == nil {
		return 0
	}
	return b.Page
}

func (b *BrowseMarketplaceCreatorsResponseMeta) GetLimit() int {
	if b == nil {
		return 0
	}
	return b.Limit
}

func (b *BrowseMarketplaceCreatorsResponseMeta) GetTotal() int {
	if b == nil {
		return 0
	}
	return b.Total
}

func (b *BrowseMarketplaceCreatorsResponseMeta) GetExtraProperties() map[string]interface{} {
	return b.extraProperties
}

func (b *BrowseMarketplaceCreatorsResponseMeta) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseMeta) SetPage(page int) {
	b.Page = page
	b.require(browseMarketplaceCreatorsResponseMetaFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseMeta) SetLimit(limit int) {
	b.Limit = limit
	b.require(browseMarketplaceCreatorsResponseMetaFieldLimit)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BrowseMarketplaceCreatorsResponseMeta) SetTotal(total int) {
	b.Total = total
	b.require(browseMarketplaceCreatorsResponseMetaFieldTotal)
}

func (b *BrowseMarketplaceCreatorsResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler BrowseMarketplaceCreatorsResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BrowseMarketplaceCreatorsResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BrowseMarketplaceCreatorsResponseMeta) MarshalJSON() ([]byte, error) {
	type embed BrowseMarketplaceCreatorsResponseMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BrowseMarketplaceCreatorsResponseMeta) String() string {
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

// Profile created
var (
	createMarketplaceCreatorProfileResponseFieldData = big.NewInt(1 << 0)
)

type CreateMarketplaceCreatorProfileResponse struct {
	Data *CreateMarketplaceCreatorProfileResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateMarketplaceCreatorProfileResponse) GetData() *CreateMarketplaceCreatorProfileResponseData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateMarketplaceCreatorProfileResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateMarketplaceCreatorProfileResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponse) SetData(data *CreateMarketplaceCreatorProfileResponseData) {
	c.Data = data
	c.require(createMarketplaceCreatorProfileResponseFieldData)
}

func (c *CreateMarketplaceCreatorProfileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateMarketplaceCreatorProfileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateMarketplaceCreatorProfileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMarketplaceCreatorProfileResponse) MarshalJSON() ([]byte, error) {
	type embed CreateMarketplaceCreatorProfileResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateMarketplaceCreatorProfileResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createMarketplaceCreatorProfileResponseDataFieldID          = big.NewInt(1 << 0)
	createMarketplaceCreatorProfileResponseDataFieldUserID      = big.NewInt(1 << 1)
	createMarketplaceCreatorProfileResponseDataFieldBio         = big.NewInt(1 << 2)
	createMarketplaceCreatorProfileResponseDataFieldWebsite     = big.NewInt(1 << 3)
	createMarketplaceCreatorProfileResponseDataFieldSocialLinks = big.NewInt(1 << 4)
	createMarketplaceCreatorProfileResponseDataFieldIsVerified  = big.NewInt(1 << 5)
	createMarketplaceCreatorProfileResponseDataFieldVerifiedAt  = big.NewInt(1 << 6)
	createMarketplaceCreatorProfileResponseDataFieldDisplayName = big.NewInt(1 << 7)
	createMarketplaceCreatorProfileResponseDataFieldUsername    = big.NewInt(1 << 8)
	createMarketplaceCreatorProfileResponseDataFieldAvatarURL   = big.NewInt(1 << 9)
	createMarketplaceCreatorProfileResponseDataFieldCreatedAt   = big.NewInt(1 << 10)
	createMarketplaceCreatorProfileResponseDataFieldUpdatedAt   = big.NewInt(1 << 11)
)

type CreateMarketplaceCreatorProfileResponseData struct {
	ID          string                 `json:"id" url:"id"`
	UserID      string                 `json:"userId" url:"userId"`
	Bio         *string                `json:"bio,omitempty" url:"bio,omitempty"`
	Website     *string                `json:"website,omitempty" url:"website,omitempty"`
	SocialLinks map[string]interface{} `json:"socialLinks,omitempty" url:"socialLinks,omitempty"`
	IsVerified  bool                   `json:"isVerified" url:"isVerified"`
	VerifiedAt  *time.Time             `json:"verifiedAt,omitempty" url:"verifiedAt,omitempty"`
	DisplayName *string                `json:"displayName,omitempty" url:"displayName,omitempty"`
	Username    *string                `json:"username,omitempty" url:"username,omitempty"`
	AvatarURL   *string                `json:"avatarUrl,omitempty" url:"avatarUrl,omitempty"`
	CreatedAt   time.Time              `json:"createdAt" url:"createdAt"`
	UpdatedAt   time.Time              `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetUserID() string {
	if c == nil {
		return ""
	}
	return c.UserID
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetBio() *string {
	if c == nil {
		return nil
	}
	return c.Bio
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetWebsite() *string {
	if c == nil {
		return nil
	}
	return c.Website
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetSocialLinks() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.SocialLinks
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetIsVerified() bool {
	if c == nil {
		return false
	}
	return c.IsVerified
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetVerifiedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.VerifiedAt
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetDisplayName() *string {
	if c == nil {
		return nil
	}
	return c.DisplayName
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetUsername() *string {
	if c == nil {
		return nil
	}
	return c.Username
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetAvatarURL() *string {
	if c == nil {
		return nil
	}
	return c.AvatarURL
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *CreateMarketplaceCreatorProfileResponseData) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateMarketplaceCreatorProfileResponseData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetID(id string) {
	c.ID = id
	c.require(createMarketplaceCreatorProfileResponseDataFieldID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetUserID(userID string) {
	c.UserID = userID
	c.require(createMarketplaceCreatorProfileResponseDataFieldUserID)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetBio(bio *string) {
	c.Bio = bio
	c.require(createMarketplaceCreatorProfileResponseDataFieldBio)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetWebsite(website *string) {
	c.Website = website
	c.require(createMarketplaceCreatorProfileResponseDataFieldWebsite)
}

// SetSocialLinks sets the SocialLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetSocialLinks(socialLinks map[string]interface{}) {
	c.SocialLinks = socialLinks
	c.require(createMarketplaceCreatorProfileResponseDataFieldSocialLinks)
}

// SetIsVerified sets the IsVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetIsVerified(isVerified bool) {
	c.IsVerified = isVerified
	c.require(createMarketplaceCreatorProfileResponseDataFieldIsVerified)
}

// SetVerifiedAt sets the VerifiedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetVerifiedAt(verifiedAt *time.Time) {
	c.VerifiedAt = verifiedAt
	c.require(createMarketplaceCreatorProfileResponseDataFieldVerifiedAt)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetDisplayName(displayName *string) {
	c.DisplayName = displayName
	c.require(createMarketplaceCreatorProfileResponseDataFieldDisplayName)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetUsername(username *string) {
	c.Username = username
	c.require(createMarketplaceCreatorProfileResponseDataFieldUsername)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetAvatarURL(avatarURL *string) {
	c.AvatarURL = avatarURL
	c.require(createMarketplaceCreatorProfileResponseDataFieldAvatarURL)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(createMarketplaceCreatorProfileResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMarketplaceCreatorProfileResponseData) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(createMarketplaceCreatorProfileResponseDataFieldUpdatedAt)
}

func (c *CreateMarketplaceCreatorProfileResponseData) UnmarshalJSON(data []byte) error {
	type embed CreateMarketplaceCreatorProfileResponseData
	var unmarshaler = struct {
		embed
		VerifiedAt *internal.DateTime `json:"verifiedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateMarketplaceCreatorProfileResponseData(unmarshaler.embed)
	c.VerifiedAt = unmarshaler.VerifiedAt.TimePtr()
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMarketplaceCreatorProfileResponseData) MarshalJSON() ([]byte, error) {
	type embed CreateMarketplaceCreatorProfileResponseData
	var marshaler = struct {
		embed
		VerifiedAt *internal.DateTime `json:"verifiedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed:      embed(*c),
		VerifiedAt: internal.NewOptionalDateTime(c.VerifiedAt),
		CreatedAt:  internal.NewDateTime(c.CreatedAt),
		UpdatedAt:  internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateMarketplaceCreatorProfileResponseData) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Public profile
var (
	getMarketplaceCreatorProfileResponseFieldData = big.NewInt(1 << 0)
)

type GetMarketplaceCreatorProfileResponse struct {
	Data *GetMarketplaceCreatorProfileResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetMarketplaceCreatorProfileResponse) GetData() *GetMarketplaceCreatorProfileResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetMarketplaceCreatorProfileResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetMarketplaceCreatorProfileResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponse) SetData(data *GetMarketplaceCreatorProfileResponseData) {
	g.Data = data
	g.require(getMarketplaceCreatorProfileResponseFieldData)
}

func (g *GetMarketplaceCreatorProfileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetMarketplaceCreatorProfileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetMarketplaceCreatorProfileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetMarketplaceCreatorProfileResponse) MarshalJSON() ([]byte, error) {
	type embed GetMarketplaceCreatorProfileResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetMarketplaceCreatorProfileResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getMarketplaceCreatorProfileResponseDataFieldID          = big.NewInt(1 << 0)
	getMarketplaceCreatorProfileResponseDataFieldUserID      = big.NewInt(1 << 1)
	getMarketplaceCreatorProfileResponseDataFieldBio         = big.NewInt(1 << 2)
	getMarketplaceCreatorProfileResponseDataFieldWebsite     = big.NewInt(1 << 3)
	getMarketplaceCreatorProfileResponseDataFieldSocialLinks = big.NewInt(1 << 4)
	getMarketplaceCreatorProfileResponseDataFieldIsVerified  = big.NewInt(1 << 5)
	getMarketplaceCreatorProfileResponseDataFieldDisplayName = big.NewInt(1 << 6)
	getMarketplaceCreatorProfileResponseDataFieldUsername    = big.NewInt(1 << 7)
	getMarketplaceCreatorProfileResponseDataFieldAvatarURL   = big.NewInt(1 << 8)
)

type GetMarketplaceCreatorProfileResponseData struct {
	ID          string                 `json:"id" url:"id"`
	UserID      string                 `json:"userId" url:"userId"`
	Bio         *string                `json:"bio,omitempty" url:"bio,omitempty"`
	Website     *string                `json:"website,omitempty" url:"website,omitempty"`
	SocialLinks map[string]interface{} `json:"socialLinks,omitempty" url:"socialLinks,omitempty"`
	IsVerified  bool                   `json:"isVerified" url:"isVerified"`
	DisplayName *string                `json:"displayName,omitempty" url:"displayName,omitempty"`
	Username    *string                `json:"username,omitempty" url:"username,omitempty"`
	AvatarURL   *string                `json:"avatarUrl,omitempty" url:"avatarUrl,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetMarketplaceCreatorProfileResponseData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetMarketplaceCreatorProfileResponseData) GetUserID() string {
	if g == nil {
		return ""
	}
	return g.UserID
}

func (g *GetMarketplaceCreatorProfileResponseData) GetBio() *string {
	if g == nil {
		return nil
	}
	return g.Bio
}

func (g *GetMarketplaceCreatorProfileResponseData) GetWebsite() *string {
	if g == nil {
		return nil
	}
	return g.Website
}

func (g *GetMarketplaceCreatorProfileResponseData) GetSocialLinks() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.SocialLinks
}

func (g *GetMarketplaceCreatorProfileResponseData) GetIsVerified() bool {
	if g == nil {
		return false
	}
	return g.IsVerified
}

func (g *GetMarketplaceCreatorProfileResponseData) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GetMarketplaceCreatorProfileResponseData) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

func (g *GetMarketplaceCreatorProfileResponseData) GetAvatarURL() *string {
	if g == nil {
		return nil
	}
	return g.AvatarURL
}

func (g *GetMarketplaceCreatorProfileResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetMarketplaceCreatorProfileResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponseData) SetID(id string) {
	g.ID = id
	g.require(getMarketplaceCreatorProfileResponseDataFieldID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponseData) SetUserID(userID string) {
	g.UserID = userID
	g.require(getMarketplaceCreatorProfileResponseDataFieldUserID)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponseData) SetBio(bio *string) {
	g.Bio = bio
	g.require(getMarketplaceCreatorProfileResponseDataFieldBio)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponseData) SetWebsite(website *string) {
	g.Website = website
	g.require(getMarketplaceCreatorProfileResponseDataFieldWebsite)
}

// SetSocialLinks sets the SocialLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponseData) SetSocialLinks(socialLinks map[string]interface{}) {
	g.SocialLinks = socialLinks
	g.require(getMarketplaceCreatorProfileResponseDataFieldSocialLinks)
}

// SetIsVerified sets the IsVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponseData) SetIsVerified(isVerified bool) {
	g.IsVerified = isVerified
	g.require(getMarketplaceCreatorProfileResponseDataFieldIsVerified)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponseData) SetDisplayName(displayName *string) {
	g.DisplayName = displayName
	g.require(getMarketplaceCreatorProfileResponseDataFieldDisplayName)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponseData) SetUsername(username *string) {
	g.Username = username
	g.require(getMarketplaceCreatorProfileResponseDataFieldUsername)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketplaceCreatorProfileResponseData) SetAvatarURL(avatarURL *string) {
	g.AvatarURL = avatarURL
	g.require(getMarketplaceCreatorProfileResponseDataFieldAvatarURL)
}

func (g *GetMarketplaceCreatorProfileResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetMarketplaceCreatorProfileResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetMarketplaceCreatorProfileResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetMarketplaceCreatorProfileResponseData) MarshalJSON() ([]byte, error) {
	type embed GetMarketplaceCreatorProfileResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetMarketplaceCreatorProfileResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Creator profile
var (
	getMyMarketplaceCreatorProfileResponseFieldData = big.NewInt(1 << 0)
)

type GetMyMarketplaceCreatorProfileResponse struct {
	Data *GetMyMarketplaceCreatorProfileResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetMyMarketplaceCreatorProfileResponse) GetData() *GetMyMarketplaceCreatorProfileResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetMyMarketplaceCreatorProfileResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetMyMarketplaceCreatorProfileResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponse) SetData(data *GetMyMarketplaceCreatorProfileResponseData) {
	g.Data = data
	g.require(getMyMarketplaceCreatorProfileResponseFieldData)
}

func (g *GetMyMarketplaceCreatorProfileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetMyMarketplaceCreatorProfileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetMyMarketplaceCreatorProfileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetMyMarketplaceCreatorProfileResponse) MarshalJSON() ([]byte, error) {
	type embed GetMyMarketplaceCreatorProfileResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetMyMarketplaceCreatorProfileResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getMyMarketplaceCreatorProfileResponseDataFieldID          = big.NewInt(1 << 0)
	getMyMarketplaceCreatorProfileResponseDataFieldUserID      = big.NewInt(1 << 1)
	getMyMarketplaceCreatorProfileResponseDataFieldBio         = big.NewInt(1 << 2)
	getMyMarketplaceCreatorProfileResponseDataFieldWebsite     = big.NewInt(1 << 3)
	getMyMarketplaceCreatorProfileResponseDataFieldSocialLinks = big.NewInt(1 << 4)
	getMyMarketplaceCreatorProfileResponseDataFieldIsVerified  = big.NewInt(1 << 5)
	getMyMarketplaceCreatorProfileResponseDataFieldVerifiedAt  = big.NewInt(1 << 6)
	getMyMarketplaceCreatorProfileResponseDataFieldDisplayName = big.NewInt(1 << 7)
	getMyMarketplaceCreatorProfileResponseDataFieldUsername    = big.NewInt(1 << 8)
	getMyMarketplaceCreatorProfileResponseDataFieldAvatarURL   = big.NewInt(1 << 9)
	getMyMarketplaceCreatorProfileResponseDataFieldCreatedAt   = big.NewInt(1 << 10)
	getMyMarketplaceCreatorProfileResponseDataFieldUpdatedAt   = big.NewInt(1 << 11)
)

type GetMyMarketplaceCreatorProfileResponseData struct {
	ID          string                 `json:"id" url:"id"`
	UserID      string                 `json:"userId" url:"userId"`
	Bio         *string                `json:"bio,omitempty" url:"bio,omitempty"`
	Website     *string                `json:"website,omitempty" url:"website,omitempty"`
	SocialLinks map[string]interface{} `json:"socialLinks,omitempty" url:"socialLinks,omitempty"`
	IsVerified  bool                   `json:"isVerified" url:"isVerified"`
	VerifiedAt  *time.Time             `json:"verifiedAt,omitempty" url:"verifiedAt,omitempty"`
	DisplayName *string                `json:"displayName,omitempty" url:"displayName,omitempty"`
	Username    *string                `json:"username,omitempty" url:"username,omitempty"`
	AvatarURL   *string                `json:"avatarUrl,omitempty" url:"avatarUrl,omitempty"`
	CreatedAt   time.Time              `json:"createdAt" url:"createdAt"`
	UpdatedAt   time.Time              `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetUserID() string {
	if g == nil {
		return ""
	}
	return g.UserID
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetBio() *string {
	if g == nil {
		return nil
	}
	return g.Bio
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetWebsite() *string {
	if g == nil {
		return nil
	}
	return g.Website
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetSocialLinks() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.SocialLinks
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetIsVerified() bool {
	if g == nil {
		return false
	}
	return g.IsVerified
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetVerifiedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.VerifiedAt
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetAvatarURL() *string {
	if g == nil {
		return nil
	}
	return g.AvatarURL
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetUpdatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.UpdatedAt
}

func (g *GetMyMarketplaceCreatorProfileResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetMyMarketplaceCreatorProfileResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetID(id string) {
	g.ID = id
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetUserID(userID string) {
	g.UserID = userID
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldUserID)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetBio(bio *string) {
	g.Bio = bio
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldBio)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetWebsite(website *string) {
	g.Website = website
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldWebsite)
}

// SetSocialLinks sets the SocialLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetSocialLinks(socialLinks map[string]interface{}) {
	g.SocialLinks = socialLinks
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldSocialLinks)
}

// SetIsVerified sets the IsVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetIsVerified(isVerified bool) {
	g.IsVerified = isVerified
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldIsVerified)
}

// SetVerifiedAt sets the VerifiedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetVerifiedAt(verifiedAt *time.Time) {
	g.VerifiedAt = verifiedAt
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldVerifiedAt)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetDisplayName(displayName *string) {
	g.DisplayName = displayName
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldDisplayName)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetUsername(username *string) {
	g.Username = username
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldUsername)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetAvatarURL(avatarURL *string) {
	g.AvatarURL = avatarURL
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldAvatarURL)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetCreatedAt(createdAt time.Time) {
	g.CreatedAt = createdAt
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyMarketplaceCreatorProfileResponseData) SetUpdatedAt(updatedAt time.Time) {
	g.UpdatedAt = updatedAt
	g.require(getMyMarketplaceCreatorProfileResponseDataFieldUpdatedAt)
}

func (g *GetMyMarketplaceCreatorProfileResponseData) UnmarshalJSON(data []byte) error {
	type embed GetMyMarketplaceCreatorProfileResponseData
	var unmarshaler = struct {
		embed
		VerifiedAt *internal.DateTime `json:"verifiedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetMyMarketplaceCreatorProfileResponseData(unmarshaler.embed)
	g.VerifiedAt = unmarshaler.VerifiedAt.TimePtr()
	g.CreatedAt = unmarshaler.CreatedAt.Time()
	g.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetMyMarketplaceCreatorProfileResponseData) MarshalJSON() ([]byte, error) {
	type embed GetMyMarketplaceCreatorProfileResponseData
	var marshaler = struct {
		embed
		VerifiedAt *internal.DateTime `json:"verifiedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed:      embed(*g),
		VerifiedAt: internal.NewOptionalDateTime(g.VerifiedAt),
		CreatedAt:  internal.NewDateTime(g.CreatedAt),
		UpdatedAt:  internal.NewDateTime(g.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetMyMarketplaceCreatorProfileResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Profile updated
var (
	updateMyMarketplaceCreatorProfileResponseFieldData = big.NewInt(1 << 0)
)

type UpdateMyMarketplaceCreatorProfileResponse struct {
	Data *UpdateMyMarketplaceCreatorProfileResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateMyMarketplaceCreatorProfileResponse) GetData() *UpdateMyMarketplaceCreatorProfileResponseData {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UpdateMyMarketplaceCreatorProfileResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateMyMarketplaceCreatorProfileResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponse) SetData(data *UpdateMyMarketplaceCreatorProfileResponseData) {
	u.Data = data
	u.require(updateMyMarketplaceCreatorProfileResponseFieldData)
}

func (u *UpdateMyMarketplaceCreatorProfileResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateMyMarketplaceCreatorProfileResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateMyMarketplaceCreatorProfileResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateMyMarketplaceCreatorProfileResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateMyMarketplaceCreatorProfileResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateMyMarketplaceCreatorProfileResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateMyMarketplaceCreatorProfileResponseDataFieldID          = big.NewInt(1 << 0)
	updateMyMarketplaceCreatorProfileResponseDataFieldUserID      = big.NewInt(1 << 1)
	updateMyMarketplaceCreatorProfileResponseDataFieldBio         = big.NewInt(1 << 2)
	updateMyMarketplaceCreatorProfileResponseDataFieldWebsite     = big.NewInt(1 << 3)
	updateMyMarketplaceCreatorProfileResponseDataFieldSocialLinks = big.NewInt(1 << 4)
	updateMyMarketplaceCreatorProfileResponseDataFieldIsVerified  = big.NewInt(1 << 5)
	updateMyMarketplaceCreatorProfileResponseDataFieldVerifiedAt  = big.NewInt(1 << 6)
	updateMyMarketplaceCreatorProfileResponseDataFieldDisplayName = big.NewInt(1 << 7)
	updateMyMarketplaceCreatorProfileResponseDataFieldUsername    = big.NewInt(1 << 8)
	updateMyMarketplaceCreatorProfileResponseDataFieldAvatarURL   = big.NewInt(1 << 9)
	updateMyMarketplaceCreatorProfileResponseDataFieldCreatedAt   = big.NewInt(1 << 10)
	updateMyMarketplaceCreatorProfileResponseDataFieldUpdatedAt   = big.NewInt(1 << 11)
)

type UpdateMyMarketplaceCreatorProfileResponseData struct {
	ID          string                 `json:"id" url:"id"`
	UserID      string                 `json:"userId" url:"userId"`
	Bio         *string                `json:"bio,omitempty" url:"bio,omitempty"`
	Website     *string                `json:"website,omitempty" url:"website,omitempty"`
	SocialLinks map[string]interface{} `json:"socialLinks,omitempty" url:"socialLinks,omitempty"`
	IsVerified  bool                   `json:"isVerified" url:"isVerified"`
	VerifiedAt  *time.Time             `json:"verifiedAt,omitempty" url:"verifiedAt,omitempty"`
	DisplayName *string                `json:"displayName,omitempty" url:"displayName,omitempty"`
	Username    *string                `json:"username,omitempty" url:"username,omitempty"`
	AvatarURL   *string                `json:"avatarUrl,omitempty" url:"avatarUrl,omitempty"`
	CreatedAt   time.Time              `json:"createdAt" url:"createdAt"`
	UpdatedAt   time.Time              `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetUserID() string {
	if u == nil {
		return ""
	}
	return u.UserID
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetBio() *string {
	if u == nil {
		return nil
	}
	return u.Bio
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetWebsite() *string {
	if u == nil {
		return nil
	}
	return u.Website
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetSocialLinks() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.SocialLinks
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetIsVerified() bool {
	if u == nil {
		return false
	}
	return u.IsVerified
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetVerifiedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.VerifiedAt
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.DisplayName
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetUsername() *string {
	if u == nil {
		return nil
	}
	return u.Username
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetAvatarURL() *string {
	if u == nil {
		return nil
	}
	return u.AvatarURL
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetCreatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.CreatedAt
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetUpdatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.UpdatedAt
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetID(id string) {
	u.ID = id
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetUserID(userID string) {
	u.UserID = userID
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldUserID)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetBio(bio *string) {
	u.Bio = bio
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldBio)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetWebsite(website *string) {
	u.Website = website
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldWebsite)
}

// SetSocialLinks sets the SocialLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetSocialLinks(socialLinks map[string]interface{}) {
	u.SocialLinks = socialLinks
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldSocialLinks)
}

// SetIsVerified sets the IsVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetIsVerified(isVerified bool) {
	u.IsVerified = isVerified
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldIsVerified)
}

// SetVerifiedAt sets the VerifiedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetVerifiedAt(verifiedAt *time.Time) {
	u.VerifiedAt = verifiedAt
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldVerifiedAt)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetDisplayName(displayName *string) {
	u.DisplayName = displayName
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldDisplayName)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetUsername(username *string) {
	u.Username = username
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldUsername)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetAvatarURL(avatarURL *string) {
	u.AvatarURL = avatarURL
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldAvatarURL)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetCreatedAt(createdAt time.Time) {
	u.CreatedAt = createdAt
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileResponseData) SetUpdatedAt(updatedAt time.Time) {
	u.UpdatedAt = updatedAt
	u.require(updateMyMarketplaceCreatorProfileResponseDataFieldUpdatedAt)
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) UnmarshalJSON(data []byte) error {
	type embed UpdateMyMarketplaceCreatorProfileResponseData
	var unmarshaler = struct {
		embed
		VerifiedAt *internal.DateTime `json:"verifiedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UpdateMyMarketplaceCreatorProfileResponseData(unmarshaler.embed)
	u.VerifiedAt = unmarshaler.VerifiedAt.TimePtr()
	u.CreatedAt = unmarshaler.CreatedAt.Time()
	u.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) MarshalJSON() ([]byte, error) {
	type embed UpdateMyMarketplaceCreatorProfileResponseData
	var marshaler = struct {
		embed
		VerifiedAt *internal.DateTime `json:"verifiedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed:      embed(*u),
		VerifiedAt: internal.NewOptionalDateTime(u.VerifiedAt),
		CreatedAt:  internal.NewDateTime(u.CreatedAt),
		UpdatedAt:  internal.NewDateTime(u.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateMyMarketplaceCreatorProfileResponseData) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateMyMarketplaceCreatorProfileRequestFieldBio         = big.NewInt(1 << 0)
	updateMyMarketplaceCreatorProfileRequestFieldWebsite     = big.NewInt(1 << 1)
	updateMyMarketplaceCreatorProfileRequestFieldSocialLinks = big.NewInt(1 << 2)
	updateMyMarketplaceCreatorProfileRequestFieldAvatarURL   = big.NewInt(1 << 3)
	updateMyMarketplaceCreatorProfileRequestFieldDisplayName = big.NewInt(1 << 4)
)

type UpdateMyMarketplaceCreatorProfileRequest struct {
	Bio         *string                `json:"bio,omitempty" url:"-"`
	Website     *string                `json:"website,omitempty" url:"-"`
	SocialLinks map[string]interface{} `json:"socialLinks,omitempty" url:"-"`
	AvatarURL   *string                `json:"avatarUrl,omitempty" url:"-"`
	DisplayName *string                `json:"displayName,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateMyMarketplaceCreatorProfileRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileRequest) SetBio(bio *string) {
	u.Bio = bio
	u.require(updateMyMarketplaceCreatorProfileRequestFieldBio)
}

// SetWebsite sets the Website field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileRequest) SetWebsite(website *string) {
	u.Website = website
	u.require(updateMyMarketplaceCreatorProfileRequestFieldWebsite)
}

// SetSocialLinks sets the SocialLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileRequest) SetSocialLinks(socialLinks map[string]interface{}) {
	u.SocialLinks = socialLinks
	u.require(updateMyMarketplaceCreatorProfileRequestFieldSocialLinks)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileRequest) SetAvatarURL(avatarURL *string) {
	u.AvatarURL = avatarURL
	u.require(updateMyMarketplaceCreatorProfileRequestFieldAvatarURL)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMyMarketplaceCreatorProfileRequest) SetDisplayName(displayName *string) {
	u.DisplayName = displayName
	u.require(updateMyMarketplaceCreatorProfileRequestFieldDisplayName)
}
