// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
)

var (
	recordResolveInstallRequestFieldRef = big.NewInt(1 << 0)
)

type RecordResolveInstallRequest struct {
	Ref string `json:"-" url:"ref"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RecordResolveInstallRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRef sets the Ref field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordResolveInstallRequest) SetRef(ref string) {
	r.Ref = ref
	r.require(recordResolveInstallRequestFieldRef)
}

var (
	resolveInstallRefRequestFieldRef = big.NewInt(1 << 0)
)

type ResolveInstallRefRequest struct {
	Ref string `json:"-" url:"ref"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ResolveInstallRefRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRef sets the Ref field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefRequest) SetRef(ref string) {
	r.Ref = ref
	r.require(resolveInstallRefRequestFieldRef)
}

// Resolved content
var (
	resolveInstallRefResponseFieldRef         = big.NewInt(1 << 0)
	resolveInstallRefResponseFieldKind        = big.NewInt(1 << 1)
	resolveInstallRefResponseFieldListingID   = big.NewInt(1 << 2)
	resolveInstallRefResponseFieldFileID      = big.NewInt(1 << 3)
	resolveInstallRefResponseFieldCreator     = big.NewInt(1 << 4)
	resolveInstallRefResponseFieldName        = big.NewInt(1 << 5)
	resolveInstallRefResponseFieldResolvedVia = big.NewInt(1 << 6)
	resolveInstallRefResponseFieldContent     = big.NewInt(1 << 7)
)

type ResolveInstallRefResponse struct {
	// Canonical namespaced ref `creator/name`, or the legacy ref when no namespace exists.
	Ref         string                               `json:"ref" url:"ref"`
	Kind        ResolveInstallRefResponseKind        `json:"kind" url:"kind"`
	ListingID   *string                              `json:"listingId,omitempty" url:"listingId,omitempty"`
	FileID      string                               `json:"fileId" url:"fileId"`
	Creator     *ResolveInstallRefResponseCreator    `json:"creator" url:"creator"`
	Name        string                               `json:"name" url:"name"`
	ResolvedVia ResolveInstallRefResponseResolvedVia `json:"resolvedVia" url:"resolvedVia"`
	Content     map[string]interface{}               `json:"content" url:"content"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResolveInstallRefResponse) GetRef() string {
	if r == nil {
		return ""
	}
	return r.Ref
}

func (r *ResolveInstallRefResponse) GetKind() ResolveInstallRefResponseKind {
	if r == nil {
		return ""
	}
	return r.Kind
}

func (r *ResolveInstallRefResponse) GetListingID() *string {
	if r == nil {
		return nil
	}
	return r.ListingID
}

func (r *ResolveInstallRefResponse) GetFileID() string {
	if r == nil {
		return ""
	}
	return r.FileID
}

func (r *ResolveInstallRefResponse) GetCreator() *ResolveInstallRefResponseCreator {
	if r == nil {
		return nil
	}
	return r.Creator
}

func (r *ResolveInstallRefResponse) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *ResolveInstallRefResponse) GetResolvedVia() ResolveInstallRefResponseResolvedVia {
	if r == nil {
		return ""
	}
	return r.ResolvedVia
}

func (r *ResolveInstallRefResponse) GetContent() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.Content
}

func (r *ResolveInstallRefResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResolveInstallRefResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRef sets the Ref field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponse) SetRef(ref string) {
	r.Ref = ref
	r.require(resolveInstallRefResponseFieldRef)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponse) SetKind(kind ResolveInstallRefResponseKind) {
	r.Kind = kind
	r.require(resolveInstallRefResponseFieldKind)
}

// SetListingID sets the ListingID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponse) SetListingID(listingID *string) {
	r.ListingID = listingID
	r.require(resolveInstallRefResponseFieldListingID)
}

// SetFileID sets the FileID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponse) SetFileID(fileID string) {
	r.FileID = fileID
	r.require(resolveInstallRefResponseFieldFileID)
}

// SetCreator sets the Creator field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponse) SetCreator(creator *ResolveInstallRefResponseCreator) {
	r.Creator = creator
	r.require(resolveInstallRefResponseFieldCreator)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponse) SetName(name string) {
	r.Name = name
	r.require(resolveInstallRefResponseFieldName)
}

// SetResolvedVia sets the ResolvedVia field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponse) SetResolvedVia(resolvedVia ResolveInstallRefResponseResolvedVia) {
	r.ResolvedVia = resolvedVia
	r.require(resolveInstallRefResponseFieldResolvedVia)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponse) SetContent(content map[string]interface{}) {
	r.Content = content
	r.require(resolveInstallRefResponseFieldContent)
}

func (r *ResolveInstallRefResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ResolveInstallRefResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResolveInstallRefResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResolveInstallRefResponse) MarshalJSON() ([]byte, error) {
	type embed ResolveInstallRefResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResolveInstallRefResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	resolveInstallRefResponseCreatorFieldUsername    = big.NewInt(1 << 0)
	resolveInstallRefResponseCreatorFieldDisplayName = big.NewInt(1 << 1)
)

type ResolveInstallRefResponseCreator struct {
	Username    *string `json:"username,omitempty" url:"username,omitempty"`
	DisplayName *string `json:"displayName,omitempty" url:"displayName,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResolveInstallRefResponseCreator) GetUsername() *string {
	if r == nil {
		return nil
	}
	return r.Username
}

func (r *ResolveInstallRefResponseCreator) GetDisplayName() *string {
	if r == nil {
		return nil
	}
	return r.DisplayName
}

func (r *ResolveInstallRefResponseCreator) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ResolveInstallRefResponseCreator) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponseCreator) SetUsername(username *string) {
	r.Username = username
	r.require(resolveInstallRefResponseCreatorFieldUsername)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResolveInstallRefResponseCreator) SetDisplayName(displayName *string) {
	r.DisplayName = displayName
	r.require(resolveInstallRefResponseCreatorFieldDisplayName)
}

func (r *ResolveInstallRefResponseCreator) UnmarshalJSON(data []byte) error {
	type unmarshaler ResolveInstallRefResponseCreator
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResolveInstallRefResponseCreator(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResolveInstallRefResponseCreator) MarshalJSON() ([]byte, error) {
	type embed ResolveInstallRefResponseCreator
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResolveInstallRefResponseCreator) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ResolveInstallRefResponseKind string

const (
	ResolveInstallRefResponseKindPrompt     ResolveInstallRefResponseKind = "prompt"
	ResolveInstallRefResponseKindSkill      ResolveInstallRefResponseKind = "skill"
	ResolveInstallRefResponseKindHook       ResolveInstallRefResponseKind = "hook"
	ResolveInstallRefResponseKindAgent      ResolveInstallRefResponseKind = "agent"
	ResolveInstallRefResponseKindMcp        ResolveInstallRefResponseKind = "mcp"
	ResolveInstallRefResponseKindCommand    ResolveInstallRefResponseKind = "command"
	ResolveInstallRefResponseKindSettings   ResolveInstallRefResponseKind = "settings"
	ResolveInstallRefResponseKindCollection ResolveInstallRefResponseKind = "collection"
)

func NewResolveInstallRefResponseKindFromString(s string) (ResolveInstallRefResponseKind, error) {
	switch s {
	case "prompt":
		return ResolveInstallRefResponseKindPrompt, nil
	case "skill":
		return ResolveInstallRefResponseKindSkill, nil
	case "hook":
		return ResolveInstallRefResponseKindHook, nil
	case "agent":
		return ResolveInstallRefResponseKindAgent, nil
	case "mcp":
		return ResolveInstallRefResponseKindMcp, nil
	case "command":
		return ResolveInstallRefResponseKindCommand, nil
	case "settings":
		return ResolveInstallRefResponseKindSettings, nil
	case "collection":
		return ResolveInstallRefResponseKindCollection, nil
	}
	var t ResolveInstallRefResponseKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ResolveInstallRefResponseKind) Ptr() *ResolveInstallRefResponseKind {
	return &r
}

type ResolveInstallRefResponseResolvedVia string

const (
	ResolveInstallRefResponseResolvedViaNamespaced     ResolveInstallRefResponseResolvedVia = "namespaced"
	ResolveInstallRefResponseResolvedViaVanity         ResolveInstallRefResponseResolvedVia = "vanity"
	ResolveInstallRefResponseResolvedViaLegacyFileSlug ResolveInstallRefResponseResolvedVia = "legacy_file_slug"
	ResolveInstallRefResponseResolvedViaBareName       ResolveInstallRefResponseResolvedVia = "bare_name"
)

func NewResolveInstallRefResponseResolvedViaFromString(s string) (ResolveInstallRefResponseResolvedVia, error) {
	switch s {
	case "namespaced":
		return ResolveInstallRefResponseResolvedViaNamespaced, nil
	case "vanity":
		return ResolveInstallRefResponseResolvedViaVanity, nil
	case "legacy_file_slug":
		return ResolveInstallRefResponseResolvedViaLegacyFileSlug, nil
	case "bare_name":
		return ResolveInstallRefResponseResolvedViaBareName, nil
	}
	var t ResolveInstallRefResponseResolvedVia
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ResolveInstallRefResponseResolvedVia) Ptr() *ResolveInstallRefResponseResolvedVia {
	return &r
}
