// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	time "time"
)

var (
	mintMcpSessionTokenRequestFieldLabel              = big.NewInt(1 << 0)
	mintMcpSessionTokenRequestFieldTTLSeconds         = big.NewInt(1 << 1)
	mintMcpSessionTokenRequestFieldDefaultWorkspaceID = big.NewInt(1 << 2)
	mintMcpSessionTokenRequestFieldScopes             = big.NewInt(1 << 3)
	mintMcpSessionTokenRequestFieldClient             = big.NewInt(1 << 4)
)

type MintMcpSessionTokenRequest struct {
	Label              *string                                `json:"label,omitempty" url:"-"`
	TTLSeconds         *int                                   `json:"ttlSeconds,omitempty" url:"-"`
	DefaultWorkspaceID *string                                `json:"defaultWorkspaceId,omitempty" url:"-"`
	Scopes             []MintMcpSessionTokenRequestScopesItem `json:"scopes,omitempty" url:"-"`
	Client             *MintMcpSessionTokenRequestClient      `json:"client,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MintMcpSessionTokenRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenRequest) SetLabel(label *string) {
	m.Label = label
	m.require(mintMcpSessionTokenRequestFieldLabel)
}

// SetTTLSeconds sets the TTLSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenRequest) SetTTLSeconds(ttlSeconds *int) {
	m.TTLSeconds = ttlSeconds
	m.require(mintMcpSessionTokenRequestFieldTTLSeconds)
}

// SetDefaultWorkspaceID sets the DefaultWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenRequest) SetDefaultWorkspaceID(defaultWorkspaceID *string) {
	m.DefaultWorkspaceID = defaultWorkspaceID
	m.require(mintMcpSessionTokenRequestFieldDefaultWorkspaceID)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenRequest) SetScopes(scopes []MintMcpSessionTokenRequestScopesItem) {
	m.Scopes = scopes
	m.require(mintMcpSessionTokenRequestFieldScopes)
}

// SetClient sets the Client field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenRequest) SetClient(client *MintMcpSessionTokenRequestClient) {
	m.Client = client
	m.require(mintMcpSessionTokenRequestFieldClient)
}

var (
	revokeMcpSessionTokenRequestFieldTokenID = big.NewInt(1 << 0)
)

type RevokeMcpSessionTokenRequest struct {
	TokenID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RevokeMcpSessionTokenRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetTokenID sets the TokenID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeMcpSessionTokenRequest) SetTokenID(tokenID string) {
	r.TokenID = tokenID
	r.require(revokeMcpSessionTokenRequestFieldTokenID)
}

// Active tokens
var (
	listMcpSessionTokensResponseFieldData = big.NewInt(1 << 0)
)

type ListMcpSessionTokensResponse struct {
	Data []*ListMcpSessionTokensResponseDataItem `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListMcpSessionTokensResponse) GetData() []*ListMcpSessionTokensResponseDataItem {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListMcpSessionTokensResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListMcpSessionTokensResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpSessionTokensResponse) SetData(data []*ListMcpSessionTokensResponseDataItem) {
	l.Data = data
	l.require(listMcpSessionTokensResponseFieldData)
}

func (l *ListMcpSessionTokensResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListMcpSessionTokensResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListMcpSessionTokensResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListMcpSessionTokensResponse) MarshalJSON() ([]byte, error) {
	type embed ListMcpSessionTokensResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListMcpSessionTokensResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listMcpSessionTokensResponseDataItemFieldTokenID            = big.NewInt(1 << 0)
	listMcpSessionTokensResponseDataItemFieldLabel              = big.NewInt(1 << 1)
	listMcpSessionTokensResponseDataItemFieldScopes             = big.NewInt(1 << 2)
	listMcpSessionTokensResponseDataItemFieldDefaultWorkspaceID = big.NewInt(1 << 3)
	listMcpSessionTokensResponseDataItemFieldIssuedAt           = big.NewInt(1 << 4)
	listMcpSessionTokensResponseDataItemFieldExpiresAt          = big.NewInt(1 << 5)
	listMcpSessionTokensResponseDataItemFieldLastUsedAt         = big.NewInt(1 << 6)
	listMcpSessionTokensResponseDataItemFieldClient             = big.NewInt(1 << 7)
)

type ListMcpSessionTokensResponseDataItem struct {
	TokenID            string                                           `json:"tokenId" url:"tokenId"`
	Label              *string                                          `json:"label,omitempty" url:"label,omitempty"`
	Scopes             []ListMcpSessionTokensResponseDataItemScopesItem `json:"scopes" url:"scopes"`
	DefaultWorkspaceID *string                                          `json:"defaultWorkspaceId,omitempty" url:"defaultWorkspaceId,omitempty"`
	IssuedAt           time.Time                                        `json:"issuedAt" url:"issuedAt"`
	ExpiresAt          time.Time                                        `json:"expiresAt" url:"expiresAt"`
	LastUsedAt         *time.Time                                       `json:"lastUsedAt,omitempty" url:"lastUsedAt,omitempty"`
	Client             *string                                          `json:"client,omitempty" url:"client,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListMcpSessionTokensResponseDataItem) GetTokenID() string {
	if l == nil {
		return ""
	}
	return l.TokenID
}

func (l *ListMcpSessionTokensResponseDataItem) GetLabel() *string {
	if l == nil {
		return nil
	}
	return l.Label
}

func (l *ListMcpSessionTokensResponseDataItem) GetScopes() []ListMcpSessionTokensResponseDataItemScopesItem {
	if l == nil {
		return nil
	}
	return l.Scopes
}

func (l *ListMcpSessionTokensResponseDataItem) GetDefaultWorkspaceID() *string {
	if l == nil {
		return nil
	}
	return l.DefaultWorkspaceID
}

func (l *ListMcpSessionTokensResponseDataItem) GetIssuedAt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.IssuedAt
}

func (l *ListMcpSessionTokensResponseDataItem) GetExpiresAt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.ExpiresAt
}

func (l *ListMcpSessionTokensResponseDataItem) GetLastUsedAt() *time.Time {
	if l == nil {
		return nil
	}
	return l.LastUsedAt
}

func (l *ListMcpSessionTokensResponseDataItem) GetClient() *string {
	if l == nil {
		return nil
	}
	return l.Client
}

func (l *ListMcpSessionTokensResponseDataItem) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListMcpSessionTokensResponseDataItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetTokenID sets the TokenID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpSessionTokensResponseDataItem) SetTokenID(tokenID string) {
	l.TokenID = tokenID
	l.require(listMcpSessionTokensResponseDataItemFieldTokenID)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpSessionTokensResponseDataItem) SetLabel(label *string) {
	l.Label = label
	l.require(listMcpSessionTokensResponseDataItemFieldLabel)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpSessionTokensResponseDataItem) SetScopes(scopes []ListMcpSessionTokensResponseDataItemScopesItem) {
	l.Scopes = scopes
	l.require(listMcpSessionTokensResponseDataItemFieldScopes)
}

// SetDefaultWorkspaceID sets the DefaultWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpSessionTokensResponseDataItem) SetDefaultWorkspaceID(defaultWorkspaceID *string) {
	l.DefaultWorkspaceID = defaultWorkspaceID
	l.require(listMcpSessionTokensResponseDataItemFieldDefaultWorkspaceID)
}

// SetIssuedAt sets the IssuedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpSessionTokensResponseDataItem) SetIssuedAt(issuedAt time.Time) {
	l.IssuedAt = issuedAt
	l.require(listMcpSessionTokensResponseDataItemFieldIssuedAt)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpSessionTokensResponseDataItem) SetExpiresAt(expiresAt time.Time) {
	l.ExpiresAt = expiresAt
	l.require(listMcpSessionTokensResponseDataItemFieldExpiresAt)
}

// SetLastUsedAt sets the LastUsedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpSessionTokensResponseDataItem) SetLastUsedAt(lastUsedAt *time.Time) {
	l.LastUsedAt = lastUsedAt
	l.require(listMcpSessionTokensResponseDataItemFieldLastUsedAt)
}

// SetClient sets the Client field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpSessionTokensResponseDataItem) SetClient(client *string) {
	l.Client = client
	l.require(listMcpSessionTokensResponseDataItemFieldClient)
}

func (l *ListMcpSessionTokensResponseDataItem) UnmarshalJSON(data []byte) error {
	type embed ListMcpSessionTokensResponseDataItem
	var unmarshaler = struct {
		embed
		IssuedAt   *internal.DateTime `json:"issuedAt"`
		ExpiresAt  *internal.DateTime `json:"expiresAt"`
		LastUsedAt *internal.DateTime `json:"lastUsedAt,omitempty"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListMcpSessionTokensResponseDataItem(unmarshaler.embed)
	l.IssuedAt = unmarshaler.IssuedAt.Time()
	l.ExpiresAt = unmarshaler.ExpiresAt.Time()
	l.LastUsedAt = unmarshaler.LastUsedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListMcpSessionTokensResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed ListMcpSessionTokensResponseDataItem
	var marshaler = struct {
		embed
		IssuedAt   *internal.DateTime `json:"issuedAt"`
		ExpiresAt  *internal.DateTime `json:"expiresAt"`
		LastUsedAt *internal.DateTime `json:"lastUsedAt,omitempty"`
	}{
		embed:      embed(*l),
		IssuedAt:   internal.NewDateTime(l.IssuedAt),
		ExpiresAt:  internal.NewDateTime(l.ExpiresAt),
		LastUsedAt: internal.NewOptionalDateTime(l.LastUsedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListMcpSessionTokensResponseDataItem) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type ListMcpSessionTokensResponseDataItemScopesItem string

const (
	ListMcpSessionTokensResponseDataItemScopesItemRead   ListMcpSessionTokensResponseDataItemScopesItem = "read"
	ListMcpSessionTokensResponseDataItemScopesItemWrite  ListMcpSessionTokensResponseDataItemScopesItem = "write"
	ListMcpSessionTokensResponseDataItemScopesItemDelete ListMcpSessionTokensResponseDataItemScopesItem = "delete"
	ListMcpSessionTokensResponseDataItemScopesItemAdmin  ListMcpSessionTokensResponseDataItemScopesItem = "admin"
)

func NewListMcpSessionTokensResponseDataItemScopesItemFromString(s string) (ListMcpSessionTokensResponseDataItemScopesItem, error) {
	switch s {
	case "read":
		return ListMcpSessionTokensResponseDataItemScopesItemRead, nil
	case "write":
		return ListMcpSessionTokensResponseDataItemScopesItemWrite, nil
	case "delete":
		return ListMcpSessionTokensResponseDataItemScopesItemDelete, nil
	case "admin":
		return ListMcpSessionTokensResponseDataItemScopesItemAdmin, nil
	}
	var t ListMcpSessionTokensResponseDataItemScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListMcpSessionTokensResponseDataItemScopesItem) Ptr() *ListMcpSessionTokensResponseDataItemScopesItem {
	return &l
}

type MintMcpSessionTokenRequestClient string

const (
	MintMcpSessionTokenRequestClientCursor   MintMcpSessionTokenRequestClient = "cursor"
	MintMcpSessionTokenRequestClientClaude   MintMcpSessionTokenRequestClient = "claude"
	MintMcpSessionTokenRequestClientWindsurf MintMcpSessionTokenRequestClient = "windsurf"
	MintMcpSessionTokenRequestClientVscode   MintMcpSessionTokenRequestClient = "vscode"
	MintMcpSessionTokenRequestClientBridge   MintMcpSessionTokenRequestClient = "bridge"
	MintMcpSessionTokenRequestClientOther    MintMcpSessionTokenRequestClient = "other"
)

func NewMintMcpSessionTokenRequestClientFromString(s string) (MintMcpSessionTokenRequestClient, error) {
	switch s {
	case "cursor":
		return MintMcpSessionTokenRequestClientCursor, nil
	case "claude":
		return MintMcpSessionTokenRequestClientClaude, nil
	case "windsurf":
		return MintMcpSessionTokenRequestClientWindsurf, nil
	case "vscode":
		return MintMcpSessionTokenRequestClientVscode, nil
	case "bridge":
		return MintMcpSessionTokenRequestClientBridge, nil
	case "other":
		return MintMcpSessionTokenRequestClientOther, nil
	}
	var t MintMcpSessionTokenRequestClient
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MintMcpSessionTokenRequestClient) Ptr() *MintMcpSessionTokenRequestClient {
	return &m
}

type MintMcpSessionTokenRequestScopesItem string

const (
	MintMcpSessionTokenRequestScopesItemRead   MintMcpSessionTokenRequestScopesItem = "read"
	MintMcpSessionTokenRequestScopesItemWrite  MintMcpSessionTokenRequestScopesItem = "write"
	MintMcpSessionTokenRequestScopesItemDelete MintMcpSessionTokenRequestScopesItem = "delete"
	MintMcpSessionTokenRequestScopesItemAdmin  MintMcpSessionTokenRequestScopesItem = "admin"
)

func NewMintMcpSessionTokenRequestScopesItemFromString(s string) (MintMcpSessionTokenRequestScopesItem, error) {
	switch s {
	case "read":
		return MintMcpSessionTokenRequestScopesItemRead, nil
	case "write":
		return MintMcpSessionTokenRequestScopesItemWrite, nil
	case "delete":
		return MintMcpSessionTokenRequestScopesItemDelete, nil
	case "admin":
		return MintMcpSessionTokenRequestScopesItemAdmin, nil
	}
	var t MintMcpSessionTokenRequestScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MintMcpSessionTokenRequestScopesItem) Ptr() *MintMcpSessionTokenRequestScopesItem {
	return &m
}

// Token minted
var (
	mintMcpSessionTokenResponseFieldData = big.NewInt(1 << 0)
)

type MintMcpSessionTokenResponse struct {
	Data *MintMcpSessionTokenResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MintMcpSessionTokenResponse) GetData() *MintMcpSessionTokenResponseData {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MintMcpSessionTokenResponse) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MintMcpSessionTokenResponse) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponse) SetData(data *MintMcpSessionTokenResponseData) {
	m.Data = data
	m.require(mintMcpSessionTokenResponseFieldData)
}

func (m *MintMcpSessionTokenResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MintMcpSessionTokenResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MintMcpSessionTokenResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MintMcpSessionTokenResponse) MarshalJSON() ([]byte, error) {
	type embed MintMcpSessionTokenResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MintMcpSessionTokenResponse) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mintMcpSessionTokenResponseDataFieldToken              = big.NewInt(1 << 0)
	mintMcpSessionTokenResponseDataFieldTokenID            = big.NewInt(1 << 1)
	mintMcpSessionTokenResponseDataFieldExpiresAt          = big.NewInt(1 << 2)
	mintMcpSessionTokenResponseDataFieldScopes             = big.NewInt(1 << 3)
	mintMcpSessionTokenResponseDataFieldDefaultWorkspaceID = big.NewInt(1 << 4)
	mintMcpSessionTokenResponseDataFieldInstructions       = big.NewInt(1 << 5)
)

type MintMcpSessionTokenResponseData struct {
	Token              string                                       `json:"token" url:"token"`
	TokenID            string                                       `json:"tokenId" url:"tokenId"`
	ExpiresAt          time.Time                                    `json:"expiresAt" url:"expiresAt"`
	Scopes             []MintMcpSessionTokenResponseDataScopesItem  `json:"scopes" url:"scopes"`
	DefaultWorkspaceID *string                                      `json:"defaultWorkspaceId,omitempty" url:"defaultWorkspaceId,omitempty"`
	Instructions       *MintMcpSessionTokenResponseDataInstructions `json:"instructions" url:"instructions"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MintMcpSessionTokenResponseData) GetToken() string {
	if m == nil {
		return ""
	}
	return m.Token
}

func (m *MintMcpSessionTokenResponseData) GetTokenID() string {
	if m == nil {
		return ""
	}
	return m.TokenID
}

func (m *MintMcpSessionTokenResponseData) GetExpiresAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.ExpiresAt
}

func (m *MintMcpSessionTokenResponseData) GetScopes() []MintMcpSessionTokenResponseDataScopesItem {
	if m == nil {
		return nil
	}
	return m.Scopes
}

func (m *MintMcpSessionTokenResponseData) GetDefaultWorkspaceID() *string {
	if m == nil {
		return nil
	}
	return m.DefaultWorkspaceID
}

func (m *MintMcpSessionTokenResponseData) GetInstructions() *MintMcpSessionTokenResponseDataInstructions {
	if m == nil {
		return nil
	}
	return m.Instructions
}

func (m *MintMcpSessionTokenResponseData) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MintMcpSessionTokenResponseData) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponseData) SetToken(token string) {
	m.Token = token
	m.require(mintMcpSessionTokenResponseDataFieldToken)
}

// SetTokenID sets the TokenID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponseData) SetTokenID(tokenID string) {
	m.TokenID = tokenID
	m.require(mintMcpSessionTokenResponseDataFieldTokenID)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponseData) SetExpiresAt(expiresAt time.Time) {
	m.ExpiresAt = expiresAt
	m.require(mintMcpSessionTokenResponseDataFieldExpiresAt)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponseData) SetScopes(scopes []MintMcpSessionTokenResponseDataScopesItem) {
	m.Scopes = scopes
	m.require(mintMcpSessionTokenResponseDataFieldScopes)
}

// SetDefaultWorkspaceID sets the DefaultWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponseData) SetDefaultWorkspaceID(defaultWorkspaceID *string) {
	m.DefaultWorkspaceID = defaultWorkspaceID
	m.require(mintMcpSessionTokenResponseDataFieldDefaultWorkspaceID)
}

// SetInstructions sets the Instructions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponseData) SetInstructions(instructions *MintMcpSessionTokenResponseDataInstructions) {
	m.Instructions = instructions
	m.require(mintMcpSessionTokenResponseDataFieldInstructions)
}

func (m *MintMcpSessionTokenResponseData) UnmarshalJSON(data []byte) error {
	type embed MintMcpSessionTokenResponseData
	var unmarshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expiresAt"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = MintMcpSessionTokenResponseData(unmarshaler.embed)
	m.ExpiresAt = unmarshaler.ExpiresAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MintMcpSessionTokenResponseData) MarshalJSON() ([]byte, error) {
	type embed MintMcpSessionTokenResponseData
	var marshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expiresAt"`
	}{
		embed:     embed(*m),
		ExpiresAt: internal.NewDateTime(m.ExpiresAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MintMcpSessionTokenResponseData) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mintMcpSessionTokenResponseDataInstructionsFieldTransport = big.NewInt(1 << 0)
	mintMcpSessionTokenResponseDataInstructionsFieldHeader    = big.NewInt(1 << 1)
	mintMcpSessionTokenResponseDataInstructionsFieldScheme    = big.NewInt(1 << 2)
)

type MintMcpSessionTokenResponseDataInstructions struct {
	Transport MintMcpSessionTokenResponseDataInstructionsTransport `json:"transport" url:"transport"`
	Header    MintMcpSessionTokenResponseDataInstructionsHeader    `json:"header" url:"header"`
	Scheme    MintMcpSessionTokenResponseDataInstructionsScheme    `json:"scheme" url:"scheme"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MintMcpSessionTokenResponseDataInstructions) GetTransport() MintMcpSessionTokenResponseDataInstructionsTransport {
	if m == nil {
		return ""
	}
	return m.Transport
}

func (m *MintMcpSessionTokenResponseDataInstructions) GetHeader() MintMcpSessionTokenResponseDataInstructionsHeader {
	if m == nil {
		return ""
	}
	return m.Header
}

func (m *MintMcpSessionTokenResponseDataInstructions) GetScheme() MintMcpSessionTokenResponseDataInstructionsScheme {
	if m == nil {
		return ""
	}
	return m.Scheme
}

func (m *MintMcpSessionTokenResponseDataInstructions) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MintMcpSessionTokenResponseDataInstructions) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetTransport sets the Transport field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponseDataInstructions) SetTransport(transport MintMcpSessionTokenResponseDataInstructionsTransport) {
	m.Transport = transport
	m.require(mintMcpSessionTokenResponseDataInstructionsFieldTransport)
}

// SetHeader sets the Header field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponseDataInstructions) SetHeader(header MintMcpSessionTokenResponseDataInstructionsHeader) {
	m.Header = header
	m.require(mintMcpSessionTokenResponseDataInstructionsFieldHeader)
}

// SetScheme sets the Scheme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MintMcpSessionTokenResponseDataInstructions) SetScheme(scheme MintMcpSessionTokenResponseDataInstructionsScheme) {
	m.Scheme = scheme
	m.require(mintMcpSessionTokenResponseDataInstructionsFieldScheme)
}

func (m *MintMcpSessionTokenResponseDataInstructions) UnmarshalJSON(data []byte) error {
	type unmarshaler MintMcpSessionTokenResponseDataInstructions
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MintMcpSessionTokenResponseDataInstructions(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MintMcpSessionTokenResponseDataInstructions) MarshalJSON() ([]byte, error) {
	type embed MintMcpSessionTokenResponseDataInstructions
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MintMcpSessionTokenResponseDataInstructions) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MintMcpSessionTokenResponseDataInstructionsHeader string

const (
	MintMcpSessionTokenResponseDataInstructionsHeaderAuthorization MintMcpSessionTokenResponseDataInstructionsHeader = "Authorization"
)

func NewMintMcpSessionTokenResponseDataInstructionsHeaderFromString(s string) (MintMcpSessionTokenResponseDataInstructionsHeader, error) {
	switch s {
	case "Authorization":
		return MintMcpSessionTokenResponseDataInstructionsHeaderAuthorization, nil
	}
	var t MintMcpSessionTokenResponseDataInstructionsHeader
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MintMcpSessionTokenResponseDataInstructionsHeader) Ptr() *MintMcpSessionTokenResponseDataInstructionsHeader {
	return &m
}

type MintMcpSessionTokenResponseDataInstructionsScheme string

const (
	MintMcpSessionTokenResponseDataInstructionsSchemeBearer MintMcpSessionTokenResponseDataInstructionsScheme = "Bearer"
)

func NewMintMcpSessionTokenResponseDataInstructionsSchemeFromString(s string) (MintMcpSessionTokenResponseDataInstructionsScheme, error) {
	switch s {
	case "Bearer":
		return MintMcpSessionTokenResponseDataInstructionsSchemeBearer, nil
	}
	var t MintMcpSessionTokenResponseDataInstructionsScheme
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MintMcpSessionTokenResponseDataInstructionsScheme) Ptr() *MintMcpSessionTokenResponseDataInstructionsScheme {
	return &m
}

type MintMcpSessionTokenResponseDataInstructionsTransport string

const (
	MintMcpSessionTokenResponseDataInstructionsTransportBearer MintMcpSessionTokenResponseDataInstructionsTransport = "bearer"
)

func NewMintMcpSessionTokenResponseDataInstructionsTransportFromString(s string) (MintMcpSessionTokenResponseDataInstructionsTransport, error) {
	switch s {
	case "bearer":
		return MintMcpSessionTokenResponseDataInstructionsTransportBearer, nil
	}
	var t MintMcpSessionTokenResponseDataInstructionsTransport
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MintMcpSessionTokenResponseDataInstructionsTransport) Ptr() *MintMcpSessionTokenResponseDataInstructionsTransport {
	return &m
}

type MintMcpSessionTokenResponseDataScopesItem string

const (
	MintMcpSessionTokenResponseDataScopesItemRead   MintMcpSessionTokenResponseDataScopesItem = "read"
	MintMcpSessionTokenResponseDataScopesItemWrite  MintMcpSessionTokenResponseDataScopesItem = "write"
	MintMcpSessionTokenResponseDataScopesItemDelete MintMcpSessionTokenResponseDataScopesItem = "delete"
	MintMcpSessionTokenResponseDataScopesItemAdmin  MintMcpSessionTokenResponseDataScopesItem = "admin"
)

func NewMintMcpSessionTokenResponseDataScopesItemFromString(s string) (MintMcpSessionTokenResponseDataScopesItem, error) {
	switch s {
	case "read":
		return MintMcpSessionTokenResponseDataScopesItemRead, nil
	case "write":
		return MintMcpSessionTokenResponseDataScopesItemWrite, nil
	case "delete":
		return MintMcpSessionTokenResponseDataScopesItemDelete, nil
	case "admin":
		return MintMcpSessionTokenResponseDataScopesItemAdmin, nil
	}
	var t MintMcpSessionTokenResponseDataScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MintMcpSessionTokenResponseDataScopesItem) Ptr() *MintMcpSessionTokenResponseDataScopesItem {
	return &m
}
