// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	big "math/big"
	time "time"
)

// Credentials valid
var (
	verifyMcpPkskInternalResponseFieldData = big.NewInt(1 << 0)
)

type VerifyMcpPkskInternalResponse struct {
	Data *VerifyMcpPkskInternalResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VerifyMcpPkskInternalResponse) GetData() *VerifyMcpPkskInternalResponseData {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *VerifyMcpPkskInternalResponse) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *VerifyMcpPkskInternalResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpPkskInternalResponse) SetData(data *VerifyMcpPkskInternalResponseData) {
	v.Data = data
	v.require(verifyMcpPkskInternalResponseFieldData)
}

func (v *VerifyMcpPkskInternalResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler VerifyMcpPkskInternalResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VerifyMcpPkskInternalResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VerifyMcpPkskInternalResponse) MarshalJSON() ([]byte, error) {
	type embed VerifyMcpPkskInternalResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VerifyMcpPkskInternalResponse) String() string {
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	verifyMcpPkskInternalResponseDataFieldKeyID     = big.NewInt(1 << 0)
	verifyMcpPkskInternalResponseDataFieldSubjectID = big.NewInt(1 << 1)
	verifyMcpPkskInternalResponseDataFieldOrgID     = big.NewInt(1 << 2)
	verifyMcpPkskInternalResponseDataFieldScopes    = big.NewInt(1 << 3)
	verifyMcpPkskInternalResponseDataFieldRevoked   = big.NewInt(1 << 4)
)

type VerifyMcpPkskInternalResponseData struct {
	KeyID     string                                        `json:"keyId" url:"keyId"`
	SubjectID string                                        `json:"subjectId" url:"subjectId"`
	OrgID     string                                        `json:"orgId" url:"orgId"`
	Scopes    []VerifyMcpPkskInternalResponseDataScopesItem `json:"scopes" url:"scopes"`
	Revoked   bool                                          `json:"revoked" url:"revoked"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VerifyMcpPkskInternalResponseData) GetKeyID() string {
	if v == nil {
		return ""
	}
	return v.KeyID
}

func (v *VerifyMcpPkskInternalResponseData) GetSubjectID() string {
	if v == nil {
		return ""
	}
	return v.SubjectID
}

func (v *VerifyMcpPkskInternalResponseData) GetOrgID() string {
	if v == nil {
		return ""
	}
	return v.OrgID
}

func (v *VerifyMcpPkskInternalResponseData) GetScopes() []VerifyMcpPkskInternalResponseDataScopesItem {
	if v == nil {
		return nil
	}
	return v.Scopes
}

func (v *VerifyMcpPkskInternalResponseData) GetRevoked() bool {
	if v == nil {
		return false
	}
	return v.Revoked
}

func (v *VerifyMcpPkskInternalResponseData) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *VerifyMcpPkskInternalResponseData) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetKeyID sets the KeyID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpPkskInternalResponseData) SetKeyID(keyID string) {
	v.KeyID = keyID
	v.require(verifyMcpPkskInternalResponseDataFieldKeyID)
}

// SetSubjectID sets the SubjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpPkskInternalResponseData) SetSubjectID(subjectID string) {
	v.SubjectID = subjectID
	v.require(verifyMcpPkskInternalResponseDataFieldSubjectID)
}

// SetOrgID sets the OrgID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpPkskInternalResponseData) SetOrgID(orgID string) {
	v.OrgID = orgID
	v.require(verifyMcpPkskInternalResponseDataFieldOrgID)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpPkskInternalResponseData) SetScopes(scopes []VerifyMcpPkskInternalResponseDataScopesItem) {
	v.Scopes = scopes
	v.require(verifyMcpPkskInternalResponseDataFieldScopes)
}

// SetRevoked sets the Revoked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpPkskInternalResponseData) SetRevoked(revoked bool) {
	v.Revoked = revoked
	v.require(verifyMcpPkskInternalResponseDataFieldRevoked)
}

func (v *VerifyMcpPkskInternalResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler VerifyMcpPkskInternalResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VerifyMcpPkskInternalResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VerifyMcpPkskInternalResponseData) MarshalJSON() ([]byte, error) {
	type embed VerifyMcpPkskInternalResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VerifyMcpPkskInternalResponseData) String() string {
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type VerifyMcpPkskInternalResponseDataScopesItem string

const (
	VerifyMcpPkskInternalResponseDataScopesItemRead   VerifyMcpPkskInternalResponseDataScopesItem = "read"
	VerifyMcpPkskInternalResponseDataScopesItemWrite  VerifyMcpPkskInternalResponseDataScopesItem = "write"
	VerifyMcpPkskInternalResponseDataScopesItemDelete VerifyMcpPkskInternalResponseDataScopesItem = "delete"
	VerifyMcpPkskInternalResponseDataScopesItemAdmin  VerifyMcpPkskInternalResponseDataScopesItem = "admin"
)

func NewVerifyMcpPkskInternalResponseDataScopesItemFromString(s string) (VerifyMcpPkskInternalResponseDataScopesItem, error) {
	switch s {
	case "read":
		return VerifyMcpPkskInternalResponseDataScopesItemRead, nil
	case "write":
		return VerifyMcpPkskInternalResponseDataScopesItemWrite, nil
	case "delete":
		return VerifyMcpPkskInternalResponseDataScopesItemDelete, nil
	case "admin":
		return VerifyMcpPkskInternalResponseDataScopesItemAdmin, nil
	}
	var t VerifyMcpPkskInternalResponseDataScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (v VerifyMcpPkskInternalResponseDataScopesItem) Ptr() *VerifyMcpPkskInternalResponseDataScopesItem {
	return &v
}

// Token valid
var (
	verifyMcpSessionTokenInternalResponseFieldData = big.NewInt(1 << 0)
)

type VerifyMcpSessionTokenInternalResponse struct {
	Data *VerifyMcpSessionTokenInternalResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VerifyMcpSessionTokenInternalResponse) GetData() *VerifyMcpSessionTokenInternalResponseData {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *VerifyMcpSessionTokenInternalResponse) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *VerifyMcpSessionTokenInternalResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpSessionTokenInternalResponse) SetData(data *VerifyMcpSessionTokenInternalResponseData) {
	v.Data = data
	v.require(verifyMcpSessionTokenInternalResponseFieldData)
}

func (v *VerifyMcpSessionTokenInternalResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler VerifyMcpSessionTokenInternalResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VerifyMcpSessionTokenInternalResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VerifyMcpSessionTokenInternalResponse) MarshalJSON() ([]byte, error) {
	type embed VerifyMcpSessionTokenInternalResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VerifyMcpSessionTokenInternalResponse) String() string {
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	verifyMcpSessionTokenInternalResponseDataFieldTokenID            = big.NewInt(1 << 0)
	verifyMcpSessionTokenInternalResponseDataFieldSubjectID          = big.NewInt(1 << 1)
	verifyMcpSessionTokenInternalResponseDataFieldOrgID              = big.NewInt(1 << 2)
	verifyMcpSessionTokenInternalResponseDataFieldDefaultWorkspaceID = big.NewInt(1 << 3)
	verifyMcpSessionTokenInternalResponseDataFieldScopes             = big.NewInt(1 << 4)
	verifyMcpSessionTokenInternalResponseDataFieldExpiresAt          = big.NewInt(1 << 5)
)

type VerifyMcpSessionTokenInternalResponseData struct {
	TokenID            string                                                `json:"tokenId" url:"tokenId"`
	SubjectID          string                                                `json:"subjectId" url:"subjectId"`
	OrgID              string                                                `json:"orgId" url:"orgId"`
	DefaultWorkspaceID *string                                               `json:"defaultWorkspaceId,omitempty" url:"defaultWorkspaceId,omitempty"`
	Scopes             []VerifyMcpSessionTokenInternalResponseDataScopesItem `json:"scopes" url:"scopes"`
	ExpiresAt          time.Time                                             `json:"expiresAt" url:"expiresAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VerifyMcpSessionTokenInternalResponseData) GetTokenID() string {
	if v == nil {
		return ""
	}
	return v.TokenID
}

func (v *VerifyMcpSessionTokenInternalResponseData) GetSubjectID() string {
	if v == nil {
		return ""
	}
	return v.SubjectID
}

func (v *VerifyMcpSessionTokenInternalResponseData) GetOrgID() string {
	if v == nil {
		return ""
	}
	return v.OrgID
}

func (v *VerifyMcpSessionTokenInternalResponseData) GetDefaultWorkspaceID() *string {
	if v == nil {
		return nil
	}
	return v.DefaultWorkspaceID
}

func (v *VerifyMcpSessionTokenInternalResponseData) GetScopes() []VerifyMcpSessionTokenInternalResponseDataScopesItem {
	if v == nil {
		return nil
	}
	return v.Scopes
}

func (v *VerifyMcpSessionTokenInternalResponseData) GetExpiresAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.ExpiresAt
}

func (v *VerifyMcpSessionTokenInternalResponseData) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *VerifyMcpSessionTokenInternalResponseData) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetTokenID sets the TokenID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpSessionTokenInternalResponseData) SetTokenID(tokenID string) {
	v.TokenID = tokenID
	v.require(verifyMcpSessionTokenInternalResponseDataFieldTokenID)
}

// SetSubjectID sets the SubjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpSessionTokenInternalResponseData) SetSubjectID(subjectID string) {
	v.SubjectID = subjectID
	v.require(verifyMcpSessionTokenInternalResponseDataFieldSubjectID)
}

// SetOrgID sets the OrgID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpSessionTokenInternalResponseData) SetOrgID(orgID string) {
	v.OrgID = orgID
	v.require(verifyMcpSessionTokenInternalResponseDataFieldOrgID)
}

// SetDefaultWorkspaceID sets the DefaultWorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpSessionTokenInternalResponseData) SetDefaultWorkspaceID(defaultWorkspaceID *string) {
	v.DefaultWorkspaceID = defaultWorkspaceID
	v.require(verifyMcpSessionTokenInternalResponseDataFieldDefaultWorkspaceID)
}

// SetScopes sets the Scopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpSessionTokenInternalResponseData) SetScopes(scopes []VerifyMcpSessionTokenInternalResponseDataScopesItem) {
	v.Scopes = scopes
	v.require(verifyMcpSessionTokenInternalResponseDataFieldScopes)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpSessionTokenInternalResponseData) SetExpiresAt(expiresAt time.Time) {
	v.ExpiresAt = expiresAt
	v.require(verifyMcpSessionTokenInternalResponseDataFieldExpiresAt)
}

func (v *VerifyMcpSessionTokenInternalResponseData) UnmarshalJSON(data []byte) error {
	type embed VerifyMcpSessionTokenInternalResponseData
	var unmarshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expiresAt"`
	}{
		embed: embed(*v),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*v = VerifyMcpSessionTokenInternalResponseData(unmarshaler.embed)
	v.ExpiresAt = unmarshaler.ExpiresAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VerifyMcpSessionTokenInternalResponseData) MarshalJSON() ([]byte, error) {
	type embed VerifyMcpSessionTokenInternalResponseData
	var marshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expiresAt"`
	}{
		embed:     embed(*v),
		ExpiresAt: internal.NewDateTime(v.ExpiresAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VerifyMcpSessionTokenInternalResponseData) String() string {
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type VerifyMcpSessionTokenInternalResponseDataScopesItem string

const (
	VerifyMcpSessionTokenInternalResponseDataScopesItemRead   VerifyMcpSessionTokenInternalResponseDataScopesItem = "read"
	VerifyMcpSessionTokenInternalResponseDataScopesItemWrite  VerifyMcpSessionTokenInternalResponseDataScopesItem = "write"
	VerifyMcpSessionTokenInternalResponseDataScopesItemDelete VerifyMcpSessionTokenInternalResponseDataScopesItem = "delete"
	VerifyMcpSessionTokenInternalResponseDataScopesItemAdmin  VerifyMcpSessionTokenInternalResponseDataScopesItem = "admin"
)

func NewVerifyMcpSessionTokenInternalResponseDataScopesItemFromString(s string) (VerifyMcpSessionTokenInternalResponseDataScopesItem, error) {
	switch s {
	case "read":
		return VerifyMcpSessionTokenInternalResponseDataScopesItemRead, nil
	case "write":
		return VerifyMcpSessionTokenInternalResponseDataScopesItemWrite, nil
	case "delete":
		return VerifyMcpSessionTokenInternalResponseDataScopesItemDelete, nil
	case "admin":
		return VerifyMcpSessionTokenInternalResponseDataScopesItemAdmin, nil
	}
	var t VerifyMcpSessionTokenInternalResponseDataScopesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (v VerifyMcpSessionTokenInternalResponseDataScopesItem) Ptr() *VerifyMcpSessionTokenInternalResponseDataScopesItem {
	return &v
}

type WriteMcpAuditInternalRequestActorKind string

const (
	WriteMcpAuditInternalRequestActorKindSession WriteMcpAuditInternalRequestActorKind = "session"
	WriteMcpAuditInternalRequestActorKindPksk    WriteMcpAuditInternalRequestActorKind = "pksk"
)

func NewWriteMcpAuditInternalRequestActorKindFromString(s string) (WriteMcpAuditInternalRequestActorKind, error) {
	switch s {
	case "session":
		return WriteMcpAuditInternalRequestActorKindSession, nil
	case "pksk":
		return WriteMcpAuditInternalRequestActorKindPksk, nil
	}
	var t WriteMcpAuditInternalRequestActorKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WriteMcpAuditInternalRequestActorKind) Ptr() *WriteMcpAuditInternalRequestActorKind {
	return &w
}

type WriteMcpAuditInternalRequestEventType string

const (
	WriteMcpAuditInternalRequestEventTypeMcpSessionTokenUsed WriteMcpAuditInternalRequestEventType = "mcp.session_token.used"
	WriteMcpAuditInternalRequestEventTypeMcpPkskUsed         WriteMcpAuditInternalRequestEventType = "mcp.pksk.used"
	WriteMcpAuditInternalRequestEventTypeMcpToolInvoked      WriteMcpAuditInternalRequestEventType = "mcp.tool.invoked"
	WriteMcpAuditInternalRequestEventTypeMcpToolDenied       WriteMcpAuditInternalRequestEventType = "mcp.tool.denied"
	WriteMcpAuditInternalRequestEventTypeMcpToolFailed       WriteMcpAuditInternalRequestEventType = "mcp.tool.failed"
	WriteMcpAuditInternalRequestEventTypeMcpResourceRead     WriteMcpAuditInternalRequestEventType = "mcp.resource.read"
	WriteMcpAuditInternalRequestEventTypeMcpPromptInvoked    WriteMcpAuditInternalRequestEventType = "mcp.prompt.invoked"
)

func NewWriteMcpAuditInternalRequestEventTypeFromString(s string) (WriteMcpAuditInternalRequestEventType, error) {
	switch s {
	case "mcp.session_token.used":
		return WriteMcpAuditInternalRequestEventTypeMcpSessionTokenUsed, nil
	case "mcp.pksk.used":
		return WriteMcpAuditInternalRequestEventTypeMcpPkskUsed, nil
	case "mcp.tool.invoked":
		return WriteMcpAuditInternalRequestEventTypeMcpToolInvoked, nil
	case "mcp.tool.denied":
		return WriteMcpAuditInternalRequestEventTypeMcpToolDenied, nil
	case "mcp.tool.failed":
		return WriteMcpAuditInternalRequestEventTypeMcpToolFailed, nil
	case "mcp.resource.read":
		return WriteMcpAuditInternalRequestEventTypeMcpResourceRead, nil
	case "mcp.prompt.invoked":
		return WriteMcpAuditInternalRequestEventTypeMcpPromptInvoked, nil
	}
	var t WriteMcpAuditInternalRequestEventType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WriteMcpAuditInternalRequestEventType) Ptr() *WriteMcpAuditInternalRequestEventType {
	return &w
}

type WriteMcpAuditInternalRequestResult string

const (
	WriteMcpAuditInternalRequestResultSuccess     WriteMcpAuditInternalRequestResult = "success"
	WriteMcpAuditInternalRequestResultClientError WriteMcpAuditInternalRequestResult = "client_error"
	WriteMcpAuditInternalRequestResultServerError WriteMcpAuditInternalRequestResult = "server_error"
	WriteMcpAuditInternalRequestResultDenied      WriteMcpAuditInternalRequestResult = "denied"
)

func NewWriteMcpAuditInternalRequestResultFromString(s string) (WriteMcpAuditInternalRequestResult, error) {
	switch s {
	case "success":
		return WriteMcpAuditInternalRequestResultSuccess, nil
	case "client_error":
		return WriteMcpAuditInternalRequestResultClientError, nil
	case "server_error":
		return WriteMcpAuditInternalRequestResultServerError, nil
	case "denied":
		return WriteMcpAuditInternalRequestResultDenied, nil
	}
	var t WriteMcpAuditInternalRequestResult
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WriteMcpAuditInternalRequestResult) Ptr() *WriteMcpAuditInternalRequestResult {
	return &w
}

// Accepted
var (
	writeMcpAuditInternalResponseFieldData = big.NewInt(1 << 0)
)

type WriteMcpAuditInternalResponse struct {
	Data *WriteMcpAuditInternalResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WriteMcpAuditInternalResponse) GetData() *WriteMcpAuditInternalResponseData {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WriteMcpAuditInternalResponse) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WriteMcpAuditInternalResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalResponse) SetData(data *WriteMcpAuditInternalResponseData) {
	w.Data = data
	w.require(writeMcpAuditInternalResponseFieldData)
}

func (w *WriteMcpAuditInternalResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WriteMcpAuditInternalResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WriteMcpAuditInternalResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WriteMcpAuditInternalResponse) MarshalJSON() ([]byte, error) {
	type embed WriteMcpAuditInternalResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WriteMcpAuditInternalResponse) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	writeMcpAuditInternalResponseDataFieldAccepted = big.NewInt(1 << 0)
)

type WriteMcpAuditInternalResponseData struct {
	Accepted bool `json:"accepted" url:"accepted"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WriteMcpAuditInternalResponseData) GetAccepted() bool {
	if w == nil {
		return false
	}
	return w.Accepted
}

func (w *WriteMcpAuditInternalResponseData) GetExtraProperties() map[string]interface{} {
	return w.extraProperties
}

func (w *WriteMcpAuditInternalResponseData) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetAccepted sets the Accepted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalResponseData) SetAccepted(accepted bool) {
	w.Accepted = accepted
	w.require(writeMcpAuditInternalResponseDataFieldAccepted)
}

func (w *WriteMcpAuditInternalResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler WriteMcpAuditInternalResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WriteMcpAuditInternalResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WriteMcpAuditInternalResponseData) MarshalJSON() ([]byte, error) {
	type embed WriteMcpAuditInternalResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WriteMcpAuditInternalResponseData) String() string {
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	verifyMcpPkskInternalRequestFieldPublicKey = big.NewInt(1 << 0)
	verifyMcpPkskInternalRequestFieldSecretKey = big.NewInt(1 << 1)
)

type VerifyMcpPkskInternalRequest struct {
	PublicKey string `json:"publicKey" url:"-"`
	SecretKey string `json:"secretKey" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VerifyMcpPkskInternalRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetPublicKey sets the PublicKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpPkskInternalRequest) SetPublicKey(publicKey string) {
	v.PublicKey = publicKey
	v.require(verifyMcpPkskInternalRequestFieldPublicKey)
}

// SetSecretKey sets the SecretKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpPkskInternalRequest) SetSecretKey(secretKey string) {
	v.SecretKey = secretKey
	v.require(verifyMcpPkskInternalRequestFieldSecretKey)
}

var (
	verifyMcpSessionTokenInternalRequestFieldToken = big.NewInt(1 << 0)
)

type VerifyMcpSessionTokenInternalRequest struct {
	Token string `json:"token" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VerifyMcpSessionTokenInternalRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyMcpSessionTokenInternalRequest) SetToken(token string) {
	v.Token = token
	v.require(verifyMcpSessionTokenInternalRequestFieldToken)
}

var (
	writeMcpAuditInternalRequestFieldEventID         = big.NewInt(1 << 0)
	writeMcpAuditInternalRequestFieldEventType       = big.NewInt(1 << 1)
	writeMcpAuditInternalRequestFieldOccurredAt      = big.NewInt(1 << 2)
	writeMcpAuditInternalRequestFieldActorSubjectID  = big.NewInt(1 << 3)
	writeMcpAuditInternalRequestFieldActorKind       = big.NewInt(1 << 4)
	writeMcpAuditInternalRequestFieldOrgID           = big.NewInt(1 << 5)
	writeMcpAuditInternalRequestFieldWorkspaceID     = big.NewInt(1 << 6)
	writeMcpAuditInternalRequestFieldToolName        = big.NewInt(1 << 7)
	writeMcpAuditInternalRequestFieldRequestID       = big.NewInt(1 << 8)
	writeMcpAuditInternalRequestFieldClientUserAgent = big.NewInt(1 << 9)
	writeMcpAuditInternalRequestFieldClientIPHash    = big.NewInt(1 << 10)
	writeMcpAuditInternalRequestFieldResult          = big.NewInt(1 << 11)
)

type WriteMcpAuditInternalRequest struct {
	EventID         string                                `json:"eventId" url:"-"`
	EventType       WriteMcpAuditInternalRequestEventType `json:"eventType" url:"-"`
	OccurredAt      time.Time                             `json:"occurredAt" url:"-"`
	ActorSubjectID  string                                `json:"actorSubjectId" url:"-"`
	ActorKind       WriteMcpAuditInternalRequestActorKind `json:"actorKind" url:"-"`
	OrgID           string                                `json:"orgId" url:"-"`
	WorkspaceID     *string                               `json:"workspaceId,omitempty" url:"-"`
	ToolName        *string                               `json:"toolName,omitempty" url:"-"`
	RequestID       string                                `json:"requestId" url:"-"`
	ClientUserAgent *string                               `json:"clientUserAgent,omitempty" url:"-"`
	ClientIPHash    string                                `json:"clientIpHash" url:"-"`
	Result          WriteMcpAuditInternalRequestResult    `json:"result" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WriteMcpAuditInternalRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetEventID sets the EventID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetEventID(eventID string) {
	w.EventID = eventID
	w.require(writeMcpAuditInternalRequestFieldEventID)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetEventType(eventType WriteMcpAuditInternalRequestEventType) {
	w.EventType = eventType
	w.require(writeMcpAuditInternalRequestFieldEventType)
}

// SetOccurredAt sets the OccurredAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetOccurredAt(occurredAt time.Time) {
	w.OccurredAt = occurredAt
	w.require(writeMcpAuditInternalRequestFieldOccurredAt)
}

// SetActorSubjectID sets the ActorSubjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetActorSubjectID(actorSubjectID string) {
	w.ActorSubjectID = actorSubjectID
	w.require(writeMcpAuditInternalRequestFieldActorSubjectID)
}

// SetActorKind sets the ActorKind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetActorKind(actorKind WriteMcpAuditInternalRequestActorKind) {
	w.ActorKind = actorKind
	w.require(writeMcpAuditInternalRequestFieldActorKind)
}

// SetOrgID sets the OrgID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetOrgID(orgID string) {
	w.OrgID = orgID
	w.require(writeMcpAuditInternalRequestFieldOrgID)
}

// SetWorkspaceID sets the WorkspaceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetWorkspaceID(workspaceID *string) {
	w.WorkspaceID = workspaceID
	w.require(writeMcpAuditInternalRequestFieldWorkspaceID)
}

// SetToolName sets the ToolName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetToolName(toolName *string) {
	w.ToolName = toolName
	w.require(writeMcpAuditInternalRequestFieldToolName)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetRequestID(requestID string) {
	w.RequestID = requestID
	w.require(writeMcpAuditInternalRequestFieldRequestID)
}

// SetClientUserAgent sets the ClientUserAgent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetClientUserAgent(clientUserAgent *string) {
	w.ClientUserAgent = clientUserAgent
	w.require(writeMcpAuditInternalRequestFieldClientUserAgent)
}

// SetClientIPHash sets the ClientIPHash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetClientIPHash(clientIPHash string) {
	w.ClientIPHash = clientIPHash
	w.require(writeMcpAuditInternalRequestFieldClientIPHash)
}

// SetResult sets the Result field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WriteMcpAuditInternalRequest) SetResult(result WriteMcpAuditInternalRequestResult) {
	w.Result = result
	w.require(writeMcpAuditInternalRequestFieldResult)
}

func (w *WriteMcpAuditInternalRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler WriteMcpAuditInternalRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WriteMcpAuditInternalRequest(body)

	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.ExtraProperties = extraProperties
	return nil
}

func (w *WriteMcpAuditInternalRequest) MarshalJSON() ([]byte, error) {
	type embed WriteMcpAuditInternalRequest
	var marshaler = struct {
		embed
		OccurredAt *internal.DateTime `json:"occurredAt"`
	}{
		embed:      embed(*w),
		OccurredAt: internal.NewDateTime(w.OccurredAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, w.ExtraProperties)
}
