// Code generated by Fern. DO NOT EDIT.

package api

import (
	big "math/big"
)

var (
	postAPIV1OauthRegisterRequestFieldClientName              = big.NewInt(1 << 0)
	postAPIV1OauthRegisterRequestFieldRedirectURIs            = big.NewInt(1 << 1)
	postAPIV1OauthRegisterRequestFieldGrantTypes              = big.NewInt(1 << 2)
	postAPIV1OauthRegisterRequestFieldResponseTypes           = big.NewInt(1 << 3)
	postAPIV1OauthRegisterRequestFieldTokenEndpointAuthMethod = big.NewInt(1 << 4)
)

type PostAPIV1OauthRegisterRequest struct {
	ClientName              string   `json:"client_name" url:"-"`
	RedirectURIs            []string `json:"redirect_uris" url:"-"`
	GrantTypes              []string `json:"grant_types,omitempty" url:"-"`
	ResponseTypes           []string `json:"response_types,omitempty" url:"-"`
	TokenEndpointAuthMethod *string  `json:"token_endpoint_auth_method,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostAPIV1OauthRegisterRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetClientName sets the ClientName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAPIV1OauthRegisterRequest) SetClientName(clientName string) {
	p.ClientName = clientName
	p.require(postAPIV1OauthRegisterRequestFieldClientName)
}

// SetRedirectURIs sets the RedirectURIs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAPIV1OauthRegisterRequest) SetRedirectURIs(redirectURIs []string) {
	p.RedirectURIs = redirectURIs
	p.require(postAPIV1OauthRegisterRequestFieldRedirectURIs)
}

// SetGrantTypes sets the GrantTypes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAPIV1OauthRegisterRequest) SetGrantTypes(grantTypes []string) {
	p.GrantTypes = grantTypes
	p.require(postAPIV1OauthRegisterRequestFieldGrantTypes)
}

// SetResponseTypes sets the ResponseTypes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAPIV1OauthRegisterRequest) SetResponseTypes(responseTypes []string) {
	p.ResponseTypes = responseTypes
	p.require(postAPIV1OauthRegisterRequestFieldResponseTypes)
}

// SetTokenEndpointAuthMethod sets the TokenEndpointAuthMethod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAPIV1OauthRegisterRequest) SetTokenEndpointAuthMethod(tokenEndpointAuthMethod *string) {
	p.TokenEndpointAuthMethod = tokenEndpointAuthMethod
	p.require(postAPIV1OauthRegisterRequestFieldTokenEndpointAuthMethod)
}

var (
	getAPIV1OauthAuthorizeRequestFieldResponseType        = big.NewInt(1 << 0)
	getAPIV1OauthAuthorizeRequestFieldClientID            = big.NewInt(1 << 1)
	getAPIV1OauthAuthorizeRequestFieldRedirectURI         = big.NewInt(1 << 2)
	getAPIV1OauthAuthorizeRequestFieldState               = big.NewInt(1 << 3)
	getAPIV1OauthAuthorizeRequestFieldScope               = big.NewInt(1 << 4)
	getAPIV1OauthAuthorizeRequestFieldCodeChallenge       = big.NewInt(1 << 5)
	getAPIV1OauthAuthorizeRequestFieldCodeChallengeMethod = big.NewInt(1 << 6)
	getAPIV1OauthAuthorizeRequestFieldResource            = big.NewInt(1 << 7)
)

type GetAPIV1OauthAuthorizeRequest struct {
	ResponseType        string  `json:"-" url:"response_type"`
	ClientID            string  `json:"-" url:"client_id"`
	RedirectURI         string  `json:"-" url:"redirect_uri"`
	State               string  `json:"-" url:"state"`
	Scope               *string `json:"-" url:"scope,omitempty"`
	CodeChallenge       string  `json:"-" url:"code_challenge"`
	CodeChallengeMethod string  `json:"-" url:"code_challenge_method"`
	Resource            *string `json:"-" url:"resource,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetAPIV1OauthAuthorizeRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetResponseType sets the ResponseType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIV1OauthAuthorizeRequest) SetResponseType(responseType string) {
	g.ResponseType = responseType
	g.require(getAPIV1OauthAuthorizeRequestFieldResponseType)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIV1OauthAuthorizeRequest) SetClientID(clientID string) {
	g.ClientID = clientID
	g.require(getAPIV1OauthAuthorizeRequestFieldClientID)
}

// SetRedirectURI sets the RedirectURI field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIV1OauthAuthorizeRequest) SetRedirectURI(redirectURI string) {
	g.RedirectURI = redirectURI
	g.require(getAPIV1OauthAuthorizeRequestFieldRedirectURI)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIV1OauthAuthorizeRequest) SetState(state string) {
	g.State = state
	g.require(getAPIV1OauthAuthorizeRequestFieldState)
}

// SetScope sets the Scope field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIV1OauthAuthorizeRequest) SetScope(scope *string) {
	g.Scope = scope
	g.require(getAPIV1OauthAuthorizeRequestFieldScope)
}

// SetCodeChallenge sets the CodeChallenge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIV1OauthAuthorizeRequest) SetCodeChallenge(codeChallenge string) {
	g.CodeChallenge = codeChallenge
	g.require(getAPIV1OauthAuthorizeRequestFieldCodeChallenge)
}

// SetCodeChallengeMethod sets the CodeChallengeMethod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIV1OauthAuthorizeRequest) SetCodeChallengeMethod(codeChallengeMethod string) {
	g.CodeChallengeMethod = codeChallengeMethod
	g.require(getAPIV1OauthAuthorizeRequestFieldCodeChallengeMethod)
}

// SetResource sets the Resource field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAPIV1OauthAuthorizeRequest) SetResource(resource *string) {
	g.Resource = resource
	g.require(getAPIV1OauthAuthorizeRequestFieldResource)
}
