// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
	time "time"
)

var (
	dismissOnboardingResponseFieldIsComplete     = big.NewInt(1 << 0)
	dismissOnboardingResponseFieldIsDismissed    = big.NewInt(1 << 1)
	dismissOnboardingResponseFieldDismissedAt    = big.NewInt(1 << 2)
	dismissOnboardingResponseFieldCompletedSteps = big.NewInt(1 << 3)
	dismissOnboardingResponseFieldCompletedAt    = big.NewInt(1 << 4)
	dismissOnboardingResponseFieldCreatedAt      = big.NewInt(1 << 5)
	dismissOnboardingResponseFieldUpdatedAt      = big.NewInt(1 << 6)
)

type DismissOnboardingResponse struct {
	IsComplete     bool                                     `json:"isComplete" url:"isComplete"`
	IsDismissed    bool                                     `json:"isDismissed" url:"isDismissed"`
	DismissedAt    *time.Time                               `json:"dismissedAt,omitempty" url:"dismissedAt,omitempty"`
	CompletedSteps *DismissOnboardingResponseCompletedSteps `json:"completedSteps" url:"completedSteps"`
	CompletedAt    *time.Time                               `json:"completedAt,omitempty" url:"completedAt,omitempty"`
	CreatedAt      time.Time                                `json:"createdAt" url:"createdAt"`
	UpdatedAt      time.Time                                `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DismissOnboardingResponse) GetIsComplete() bool {
	if d == nil {
		return false
	}
	return d.IsComplete
}

func (d *DismissOnboardingResponse) GetIsDismissed() bool {
	if d == nil {
		return false
	}
	return d.IsDismissed
}

func (d *DismissOnboardingResponse) GetDismissedAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.DismissedAt
}

func (d *DismissOnboardingResponse) GetCompletedSteps() *DismissOnboardingResponseCompletedSteps {
	if d == nil {
		return nil
	}
	return d.CompletedSteps
}

func (d *DismissOnboardingResponse) GetCompletedAt() *time.Time {
	if d == nil {
		return nil
	}
	return d.CompletedAt
}

func (d *DismissOnboardingResponse) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DismissOnboardingResponse) GetUpdatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.UpdatedAt
}

func (d *DismissOnboardingResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DismissOnboardingResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetIsComplete sets the IsComplete field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponse) SetIsComplete(isComplete bool) {
	d.IsComplete = isComplete
	d.require(dismissOnboardingResponseFieldIsComplete)
}

// SetIsDismissed sets the IsDismissed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponse) SetIsDismissed(isDismissed bool) {
	d.IsDismissed = isDismissed
	d.require(dismissOnboardingResponseFieldIsDismissed)
}

// SetDismissedAt sets the DismissedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponse) SetDismissedAt(dismissedAt *time.Time) {
	d.DismissedAt = dismissedAt
	d.require(dismissOnboardingResponseFieldDismissedAt)
}

// SetCompletedSteps sets the CompletedSteps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponse) SetCompletedSteps(completedSteps *DismissOnboardingResponseCompletedSteps) {
	d.CompletedSteps = completedSteps
	d.require(dismissOnboardingResponseFieldCompletedSteps)
}

// SetCompletedAt sets the CompletedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponse) SetCompletedAt(completedAt *time.Time) {
	d.CompletedAt = completedAt
	d.require(dismissOnboardingResponseFieldCompletedAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponse) SetCreatedAt(createdAt time.Time) {
	d.CreatedAt = createdAt
	d.require(dismissOnboardingResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponse) SetUpdatedAt(updatedAt time.Time) {
	d.UpdatedAt = updatedAt
	d.require(dismissOnboardingResponseFieldUpdatedAt)
}

func (d *DismissOnboardingResponse) UnmarshalJSON(data []byte) error {
	type embed DismissOnboardingResponse
	var unmarshaler = struct {
		embed
		DismissedAt *internal.DateTime `json:"dismissedAt,omitempty"`
		CompletedAt *internal.DateTime `json:"completedAt,omitempty"`
		CreatedAt   *internal.DateTime `json:"createdAt"`
		UpdatedAt   *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DismissOnboardingResponse(unmarshaler.embed)
	d.DismissedAt = unmarshaler.DismissedAt.TimePtr()
	d.CompletedAt = unmarshaler.CompletedAt.TimePtr()
	d.CreatedAt = unmarshaler.CreatedAt.Time()
	d.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DismissOnboardingResponse) MarshalJSON() ([]byte, error) {
	type embed DismissOnboardingResponse
	var marshaler = struct {
		embed
		DismissedAt *internal.DateTime `json:"dismissedAt,omitempty"`
		CompletedAt *internal.DateTime `json:"completedAt,omitempty"`
		CreatedAt   *internal.DateTime `json:"createdAt"`
		UpdatedAt   *internal.DateTime `json:"updatedAt"`
	}{
		embed:       embed(*d),
		DismissedAt: internal.NewOptionalDateTime(d.DismissedAt),
		CompletedAt: internal.NewOptionalDateTime(d.CompletedAt),
		CreatedAt:   internal.NewDateTime(d.CreatedAt),
		UpdatedAt:   internal.NewDateTime(d.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DismissOnboardingResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	dismissOnboardingResponseCompletedStepsFieldFirstPrompt = big.NewInt(1 << 0)
	dismissOnboardingResponseCompletedStepsFieldTeamOrg     = big.NewInt(1 << 1)
	dismissOnboardingResponseCompletedStepsFieldTeamInvite  = big.NewInt(1 << 2)
)

type DismissOnboardingResponseCompletedSteps struct {
	FirstPrompt bool `json:"first_prompt" url:"first_prompt"`
	TeamOrg     bool `json:"team_org" url:"team_org"`
	TeamInvite  bool `json:"team_invite" url:"team_invite"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DismissOnboardingResponseCompletedSteps) GetFirstPrompt() bool {
	if d == nil {
		return false
	}
	return d.FirstPrompt
}

func (d *DismissOnboardingResponseCompletedSteps) GetTeamOrg() bool {
	if d == nil {
		return false
	}
	return d.TeamOrg
}

func (d *DismissOnboardingResponseCompletedSteps) GetTeamInvite() bool {
	if d == nil {
		return false
	}
	return d.TeamInvite
}

func (d *DismissOnboardingResponseCompletedSteps) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DismissOnboardingResponseCompletedSteps) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetFirstPrompt sets the FirstPrompt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponseCompletedSteps) SetFirstPrompt(firstPrompt bool) {
	d.FirstPrompt = firstPrompt
	d.require(dismissOnboardingResponseCompletedStepsFieldFirstPrompt)
}

// SetTeamOrg sets the TeamOrg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponseCompletedSteps) SetTeamOrg(teamOrg bool) {
	d.TeamOrg = teamOrg
	d.require(dismissOnboardingResponseCompletedStepsFieldTeamOrg)
}

// SetTeamInvite sets the TeamInvite field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DismissOnboardingResponseCompletedSteps) SetTeamInvite(teamInvite bool) {
	d.TeamInvite = teamInvite
	d.require(dismissOnboardingResponseCompletedStepsFieldTeamInvite)
}

func (d *DismissOnboardingResponseCompletedSteps) UnmarshalJSON(data []byte) error {
	type unmarshaler DismissOnboardingResponseCompletedSteps
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DismissOnboardingResponseCompletedSteps(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DismissOnboardingResponseCompletedSteps) MarshalJSON() ([]byte, error) {
	type embed DismissOnboardingResponseCompletedSteps
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DismissOnboardingResponseCompletedSteps) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getOnboardingStatusResponseFieldIsComplete     = big.NewInt(1 << 0)
	getOnboardingStatusResponseFieldIsDismissed    = big.NewInt(1 << 1)
	getOnboardingStatusResponseFieldDismissedAt    = big.NewInt(1 << 2)
	getOnboardingStatusResponseFieldCompletedSteps = big.NewInt(1 << 3)
	getOnboardingStatusResponseFieldCompletedAt    = big.NewInt(1 << 4)
	getOnboardingStatusResponseFieldCreatedAt      = big.NewInt(1 << 5)
	getOnboardingStatusResponseFieldUpdatedAt      = big.NewInt(1 << 6)
)

type GetOnboardingStatusResponse struct {
	IsComplete     bool                                       `json:"isComplete" url:"isComplete"`
	IsDismissed    bool                                       `json:"isDismissed" url:"isDismissed"`
	DismissedAt    *time.Time                                 `json:"dismissedAt,omitempty" url:"dismissedAt,omitempty"`
	CompletedSteps *GetOnboardingStatusResponseCompletedSteps `json:"completedSteps" url:"completedSteps"`
	CompletedAt    *time.Time                                 `json:"completedAt,omitempty" url:"completedAt,omitempty"`
	CreatedAt      time.Time                                  `json:"createdAt" url:"createdAt"`
	UpdatedAt      time.Time                                  `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetOnboardingStatusResponse) GetIsComplete() bool {
	if g == nil {
		return false
	}
	return g.IsComplete
}

func (g *GetOnboardingStatusResponse) GetIsDismissed() bool {
	if g == nil {
		return false
	}
	return g.IsDismissed
}

func (g *GetOnboardingStatusResponse) GetDismissedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.DismissedAt
}

func (g *GetOnboardingStatusResponse) GetCompletedSteps() *GetOnboardingStatusResponseCompletedSteps {
	if g == nil {
		return nil
	}
	return g.CompletedSteps
}

func (g *GetOnboardingStatusResponse) GetCompletedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.CompletedAt
}

func (g *GetOnboardingStatusResponse) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GetOnboardingStatusResponse) GetUpdatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.UpdatedAt
}

func (g *GetOnboardingStatusResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetOnboardingStatusResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetIsComplete sets the IsComplete field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponse) SetIsComplete(isComplete bool) {
	g.IsComplete = isComplete
	g.require(getOnboardingStatusResponseFieldIsComplete)
}

// SetIsDismissed sets the IsDismissed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponse) SetIsDismissed(isDismissed bool) {
	g.IsDismissed = isDismissed
	g.require(getOnboardingStatusResponseFieldIsDismissed)
}

// SetDismissedAt sets the DismissedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponse) SetDismissedAt(dismissedAt *time.Time) {
	g.DismissedAt = dismissedAt
	g.require(getOnboardingStatusResponseFieldDismissedAt)
}

// SetCompletedSteps sets the CompletedSteps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponse) SetCompletedSteps(completedSteps *GetOnboardingStatusResponseCompletedSteps) {
	g.CompletedSteps = completedSteps
	g.require(getOnboardingStatusResponseFieldCompletedSteps)
}

// SetCompletedAt sets the CompletedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponse) SetCompletedAt(completedAt *time.Time) {
	g.CompletedAt = completedAt
	g.require(getOnboardingStatusResponseFieldCompletedAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponse) SetCreatedAt(createdAt time.Time) {
	g.CreatedAt = createdAt
	g.require(getOnboardingStatusResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponse) SetUpdatedAt(updatedAt time.Time) {
	g.UpdatedAt = updatedAt
	g.require(getOnboardingStatusResponseFieldUpdatedAt)
}

func (g *GetOnboardingStatusResponse) UnmarshalJSON(data []byte) error {
	type embed GetOnboardingStatusResponse
	var unmarshaler = struct {
		embed
		DismissedAt *internal.DateTime `json:"dismissedAt,omitempty"`
		CompletedAt *internal.DateTime `json:"completedAt,omitempty"`
		CreatedAt   *internal.DateTime `json:"createdAt"`
		UpdatedAt   *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetOnboardingStatusResponse(unmarshaler.embed)
	g.DismissedAt = unmarshaler.DismissedAt.TimePtr()
	g.CompletedAt = unmarshaler.CompletedAt.TimePtr()
	g.CreatedAt = unmarshaler.CreatedAt.Time()
	g.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetOnboardingStatusResponse) MarshalJSON() ([]byte, error) {
	type embed GetOnboardingStatusResponse
	var marshaler = struct {
		embed
		DismissedAt *internal.DateTime `json:"dismissedAt,omitempty"`
		CompletedAt *internal.DateTime `json:"completedAt,omitempty"`
		CreatedAt   *internal.DateTime `json:"createdAt"`
		UpdatedAt   *internal.DateTime `json:"updatedAt"`
	}{
		embed:       embed(*g),
		DismissedAt: internal.NewOptionalDateTime(g.DismissedAt),
		CompletedAt: internal.NewOptionalDateTime(g.CompletedAt),
		CreatedAt:   internal.NewDateTime(g.CreatedAt),
		UpdatedAt:   internal.NewDateTime(g.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetOnboardingStatusResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getOnboardingStatusResponseCompletedStepsFieldFirstPrompt = big.NewInt(1 << 0)
	getOnboardingStatusResponseCompletedStepsFieldTeamOrg     = big.NewInt(1 << 1)
	getOnboardingStatusResponseCompletedStepsFieldTeamInvite  = big.NewInt(1 << 2)
)

type GetOnboardingStatusResponseCompletedSteps struct {
	FirstPrompt bool `json:"first_prompt" url:"first_prompt"`
	TeamOrg     bool `json:"team_org" url:"team_org"`
	TeamInvite  bool `json:"team_invite" url:"team_invite"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetOnboardingStatusResponseCompletedSteps) GetFirstPrompt() bool {
	if g == nil {
		return false
	}
	return g.FirstPrompt
}

func (g *GetOnboardingStatusResponseCompletedSteps) GetTeamOrg() bool {
	if g == nil {
		return false
	}
	return g.TeamOrg
}

func (g *GetOnboardingStatusResponseCompletedSteps) GetTeamInvite() bool {
	if g == nil {
		return false
	}
	return g.TeamInvite
}

func (g *GetOnboardingStatusResponseCompletedSteps) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetOnboardingStatusResponseCompletedSteps) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetFirstPrompt sets the FirstPrompt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponseCompletedSteps) SetFirstPrompt(firstPrompt bool) {
	g.FirstPrompt = firstPrompt
	g.require(getOnboardingStatusResponseCompletedStepsFieldFirstPrompt)
}

// SetTeamOrg sets the TeamOrg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponseCompletedSteps) SetTeamOrg(teamOrg bool) {
	g.TeamOrg = teamOrg
	g.require(getOnboardingStatusResponseCompletedStepsFieldTeamOrg)
}

// SetTeamInvite sets the TeamInvite field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOnboardingStatusResponseCompletedSteps) SetTeamInvite(teamInvite bool) {
	g.TeamInvite = teamInvite
	g.require(getOnboardingStatusResponseCompletedStepsFieldTeamInvite)
}

func (g *GetOnboardingStatusResponseCompletedSteps) UnmarshalJSON(data []byte) error {
	type unmarshaler GetOnboardingStatusResponseCompletedSteps
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetOnboardingStatusResponseCompletedSteps(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetOnboardingStatusResponseCompletedSteps) MarshalJSON() ([]byte, error) {
	type embed GetOnboardingStatusResponseCompletedSteps
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetOnboardingStatusResponseCompletedSteps) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type UpdateOnboardingStepRequestStep string

const (
	UpdateOnboardingStepRequestStepFirstPrompt UpdateOnboardingStepRequestStep = "first_prompt"
	UpdateOnboardingStepRequestStepTeamOrg     UpdateOnboardingStepRequestStep = "team_org"
	UpdateOnboardingStepRequestStepTeamInvite  UpdateOnboardingStepRequestStep = "team_invite"
)

func NewUpdateOnboardingStepRequestStepFromString(s string) (UpdateOnboardingStepRequestStep, error) {
	switch s {
	case "first_prompt":
		return UpdateOnboardingStepRequestStepFirstPrompt, nil
	case "team_org":
		return UpdateOnboardingStepRequestStepTeamOrg, nil
	case "team_invite":
		return UpdateOnboardingStepRequestStepTeamInvite, nil
	}
	var t UpdateOnboardingStepRequestStep
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateOnboardingStepRequestStep) Ptr() *UpdateOnboardingStepRequestStep {
	return &u
}

var (
	updateOnboardingStepResponseFieldIsComplete     = big.NewInt(1 << 0)
	updateOnboardingStepResponseFieldIsDismissed    = big.NewInt(1 << 1)
	updateOnboardingStepResponseFieldDismissedAt    = big.NewInt(1 << 2)
	updateOnboardingStepResponseFieldCompletedSteps = big.NewInt(1 << 3)
	updateOnboardingStepResponseFieldCompletedAt    = big.NewInt(1 << 4)
	updateOnboardingStepResponseFieldCreatedAt      = big.NewInt(1 << 5)
	updateOnboardingStepResponseFieldUpdatedAt      = big.NewInt(1 << 6)
)

type UpdateOnboardingStepResponse struct {
	IsComplete     bool                                        `json:"isComplete" url:"isComplete"`
	IsDismissed    bool                                        `json:"isDismissed" url:"isDismissed"`
	DismissedAt    *time.Time                                  `json:"dismissedAt,omitempty" url:"dismissedAt,omitempty"`
	CompletedSteps *UpdateOnboardingStepResponseCompletedSteps `json:"completedSteps" url:"completedSteps"`
	CompletedAt    *time.Time                                  `json:"completedAt,omitempty" url:"completedAt,omitempty"`
	CreatedAt      time.Time                                   `json:"createdAt" url:"createdAt"`
	UpdatedAt      time.Time                                   `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateOnboardingStepResponse) GetIsComplete() bool {
	if u == nil {
		return false
	}
	return u.IsComplete
}

func (u *UpdateOnboardingStepResponse) GetIsDismissed() bool {
	if u == nil {
		return false
	}
	return u.IsDismissed
}

func (u *UpdateOnboardingStepResponse) GetDismissedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.DismissedAt
}

func (u *UpdateOnboardingStepResponse) GetCompletedSteps() *UpdateOnboardingStepResponseCompletedSteps {
	if u == nil {
		return nil
	}
	return u.CompletedSteps
}

func (u *UpdateOnboardingStepResponse) GetCompletedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.CompletedAt
}

func (u *UpdateOnboardingStepResponse) GetCreatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.CreatedAt
}

func (u *UpdateOnboardingStepResponse) GetUpdatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.UpdatedAt
}

func (u *UpdateOnboardingStepResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateOnboardingStepResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetIsComplete sets the IsComplete field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponse) SetIsComplete(isComplete bool) {
	u.IsComplete = isComplete
	u.require(updateOnboardingStepResponseFieldIsComplete)
}

// SetIsDismissed sets the IsDismissed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponse) SetIsDismissed(isDismissed bool) {
	u.IsDismissed = isDismissed
	u.require(updateOnboardingStepResponseFieldIsDismissed)
}

// SetDismissedAt sets the DismissedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponse) SetDismissedAt(dismissedAt *time.Time) {
	u.DismissedAt = dismissedAt
	u.require(updateOnboardingStepResponseFieldDismissedAt)
}

// SetCompletedSteps sets the CompletedSteps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponse) SetCompletedSteps(completedSteps *UpdateOnboardingStepResponseCompletedSteps) {
	u.CompletedSteps = completedSteps
	u.require(updateOnboardingStepResponseFieldCompletedSteps)
}

// SetCompletedAt sets the CompletedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponse) SetCompletedAt(completedAt *time.Time) {
	u.CompletedAt = completedAt
	u.require(updateOnboardingStepResponseFieldCompletedAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponse) SetCreatedAt(createdAt time.Time) {
	u.CreatedAt = createdAt
	u.require(updateOnboardingStepResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponse) SetUpdatedAt(updatedAt time.Time) {
	u.UpdatedAt = updatedAt
	u.require(updateOnboardingStepResponseFieldUpdatedAt)
}

func (u *UpdateOnboardingStepResponse) UnmarshalJSON(data []byte) error {
	type embed UpdateOnboardingStepResponse
	var unmarshaler = struct {
		embed
		DismissedAt *internal.DateTime `json:"dismissedAt,omitempty"`
		CompletedAt *internal.DateTime `json:"completedAt,omitempty"`
		CreatedAt   *internal.DateTime `json:"createdAt"`
		UpdatedAt   *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UpdateOnboardingStepResponse(unmarshaler.embed)
	u.DismissedAt = unmarshaler.DismissedAt.TimePtr()
	u.CompletedAt = unmarshaler.CompletedAt.TimePtr()
	u.CreatedAt = unmarshaler.CreatedAt.Time()
	u.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateOnboardingStepResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateOnboardingStepResponse
	var marshaler = struct {
		embed
		DismissedAt *internal.DateTime `json:"dismissedAt,omitempty"`
		CompletedAt *internal.DateTime `json:"completedAt,omitempty"`
		CreatedAt   *internal.DateTime `json:"createdAt"`
		UpdatedAt   *internal.DateTime `json:"updatedAt"`
	}{
		embed:       embed(*u),
		DismissedAt: internal.NewOptionalDateTime(u.DismissedAt),
		CompletedAt: internal.NewOptionalDateTime(u.CompletedAt),
		CreatedAt:   internal.NewDateTime(u.CreatedAt),
		UpdatedAt:   internal.NewDateTime(u.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateOnboardingStepResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateOnboardingStepResponseCompletedStepsFieldFirstPrompt = big.NewInt(1 << 0)
	updateOnboardingStepResponseCompletedStepsFieldTeamOrg     = big.NewInt(1 << 1)
	updateOnboardingStepResponseCompletedStepsFieldTeamInvite  = big.NewInt(1 << 2)
)

type UpdateOnboardingStepResponseCompletedSteps struct {
	FirstPrompt bool `json:"first_prompt" url:"first_prompt"`
	TeamOrg     bool `json:"team_org" url:"team_org"`
	TeamInvite  bool `json:"team_invite" url:"team_invite"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateOnboardingStepResponseCompletedSteps) GetFirstPrompt() bool {
	if u == nil {
		return false
	}
	return u.FirstPrompt
}

func (u *UpdateOnboardingStepResponseCompletedSteps) GetTeamOrg() bool {
	if u == nil {
		return false
	}
	return u.TeamOrg
}

func (u *UpdateOnboardingStepResponseCompletedSteps) GetTeamInvite() bool {
	if u == nil {
		return false
	}
	return u.TeamInvite
}

func (u *UpdateOnboardingStepResponseCompletedSteps) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateOnboardingStepResponseCompletedSteps) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetFirstPrompt sets the FirstPrompt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponseCompletedSteps) SetFirstPrompt(firstPrompt bool) {
	u.FirstPrompt = firstPrompt
	u.require(updateOnboardingStepResponseCompletedStepsFieldFirstPrompt)
}

// SetTeamOrg sets the TeamOrg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponseCompletedSteps) SetTeamOrg(teamOrg bool) {
	u.TeamOrg = teamOrg
	u.require(updateOnboardingStepResponseCompletedStepsFieldTeamOrg)
}

// SetTeamInvite sets the TeamInvite field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepResponseCompletedSteps) SetTeamInvite(teamInvite bool) {
	u.TeamInvite = teamInvite
	u.require(updateOnboardingStepResponseCompletedStepsFieldTeamInvite)
}

func (u *UpdateOnboardingStepResponseCompletedSteps) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateOnboardingStepResponseCompletedSteps
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateOnboardingStepResponseCompletedSteps(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateOnboardingStepResponseCompletedSteps) MarshalJSON() ([]byte, error) {
	type embed UpdateOnboardingStepResponseCompletedSteps
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateOnboardingStepResponseCompletedSteps) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateOnboardingStepRequestFieldStep      = big.NewInt(1 << 0)
	updateOnboardingStepRequestFieldCompleted = big.NewInt(1 << 1)
)

type UpdateOnboardingStepRequest struct {
	Step      UpdateOnboardingStepRequestStep `json:"step" url:"-"`
	Completed bool                            `json:"completed" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateOnboardingStepRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetStep sets the Step field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepRequest) SetStep(step UpdateOnboardingStepRequestStep) {
	u.Step = step
	u.require(updateOnboardingStepRequestFieldStep)
}

// SetCompleted sets the Completed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateOnboardingStepRequest) SetCompleted(completed bool) {
	u.Completed = completed
	u.require(updateOnboardingStepRequestFieldCompleted)
}
