// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	big "math/big"
	time "time"
)

// Bad request
var (
	badRequestErrorBodyFieldError      = big.NewInt(1 << 0)
	badRequestErrorBodyFieldStatusCode = big.NewInt(1 << 1)
)

type BadRequestErrorBody struct {
	Error      *string `json:"error,omitempty" url:"error,omitempty"`
	StatusCode *int    `json:"statusCode,omitempty" url:"statusCode,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BadRequestErrorBody) GetError() *string {
	if b == nil {
		return nil
	}
	return b.Error
}

func (b *BadRequestErrorBody) GetStatusCode() *int {
	if b == nil {
		return nil
	}
	return b.StatusCode
}

func (b *BadRequestErrorBody) GetExtraProperties() map[string]interface{} {
	return b.extraProperties
}

func (b *BadRequestErrorBody) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BadRequestErrorBody) SetError(error_ *string) {
	b.Error = error_
	b.require(badRequestErrorBodyFieldError)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BadRequestErrorBody) SetStatusCode(statusCode *int) {
	b.StatusCode = statusCode
	b.require(badRequestErrorBodyFieldStatusCode)
}

func (b *BadRequestErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler BadRequestErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BadRequestErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BadRequestErrorBody) MarshalJSON() ([]byte, error) {
	type embed BadRequestErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BadRequestErrorBody) String() string {
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	badRequestErrorBodyDetailsItemFieldField   = big.NewInt(1 << 0)
	badRequestErrorBodyDetailsItemFieldMessage = big.NewInt(1 << 1)
)

type BadRequestErrorBodyDetailsItem struct {
	// Field that failed validation
	Field string `json:"field" url:"field"`
	// Validation error message
	Message string `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BadRequestErrorBodyDetailsItem) GetField() string {
	if b == nil {
		return ""
	}
	return b.Field
}

func (b *BadRequestErrorBodyDetailsItem) GetMessage() string {
	if b == nil {
		return ""
	}
	return b.Message
}

func (b *BadRequestErrorBodyDetailsItem) GetExtraProperties() map[string]interface{} {
	return b.extraProperties
}

func (b *BadRequestErrorBodyDetailsItem) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetField sets the Field field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BadRequestErrorBodyDetailsItem) SetField(field string) {
	b.Field = field
	b.require(badRequestErrorBodyDetailsItemFieldField)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BadRequestErrorBodyDetailsItem) SetMessage(message string) {
	b.Message = message
	b.require(badRequestErrorBodyDetailsItemFieldMessage)
}

func (b *BadRequestErrorBodyDetailsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler BadRequestErrorBodyDetailsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BadRequestErrorBodyDetailsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BadRequestErrorBodyDetailsItem) MarshalJSON() ([]byte, error) {
	type embed BadRequestErrorBodyDetailsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BadRequestErrorBodyDetailsItem) String() string {
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

// Workspace has content
var (
	conflictErrorBodyFieldError          = big.NewInt(1 << 0)
	conflictErrorBodyFieldStatusCode     = big.NewInt(1 << 1)
	conflictErrorBodyFieldPromptCount    = big.NewInt(1 << 2)
	conflictErrorBodyFieldDirectoryCount = big.NewInt(1 << 3)
)

type ConflictErrorBody struct {
	Error          *string `json:"error,omitempty" url:"error,omitempty"`
	StatusCode     *int    `json:"statusCode,omitempty" url:"statusCode,omitempty"`
	PromptCount    *int    `json:"promptCount,omitempty" url:"promptCount,omitempty"`
	DirectoryCount *int    `json:"directoryCount,omitempty" url:"directoryCount,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConflictErrorBody) GetError() *string {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *ConflictErrorBody) GetStatusCode() *int {
	if c == nil {
		return nil
	}
	return c.StatusCode
}

func (c *ConflictErrorBody) GetPromptCount() *int {
	if c == nil {
		return nil
	}
	return c.PromptCount
}

func (c *ConflictErrorBody) GetDirectoryCount() *int {
	if c == nil {
		return nil
	}
	return c.DirectoryCount
}

func (c *ConflictErrorBody) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ConflictErrorBody) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConflictErrorBody) SetError(error_ *string) {
	c.Error = error_
	c.require(conflictErrorBodyFieldError)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConflictErrorBody) SetStatusCode(statusCode *int) {
	c.StatusCode = statusCode
	c.require(conflictErrorBodyFieldStatusCode)
}

// SetPromptCount sets the PromptCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConflictErrorBody) SetPromptCount(promptCount *int) {
	c.PromptCount = promptCount
	c.require(conflictErrorBodyFieldPromptCount)
}

// SetDirectoryCount sets the DirectoryCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConflictErrorBody) SetDirectoryCount(directoryCount *int) {
	c.DirectoryCount = directoryCount
	c.require(conflictErrorBodyFieldDirectoryCount)
}

func (c *ConflictErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler ConflictErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConflictErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConflictErrorBody) MarshalJSON() ([]byte, error) {
	type embed ConflictErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConflictErrorBody) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Forbidden
var (
	forbiddenErrorBodyFieldError      = big.NewInt(1 << 0)
	forbiddenErrorBodyFieldStatusCode = big.NewInt(1 << 1)
)

type ForbiddenErrorBody struct {
	Error      *string `json:"error,omitempty" url:"error,omitempty"`
	StatusCode *int    `json:"statusCode,omitempty" url:"statusCode,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *ForbiddenErrorBody) GetError() *string {
	if f == nil {
		return nil
	}
	return f.Error
}

func (f *ForbiddenErrorBody) GetStatusCode() *int {
	if f == nil {
		return nil
	}
	return f.StatusCode
}

func (f *ForbiddenErrorBody) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *ForbiddenErrorBody) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBody) SetError(error_ *string) {
	f.Error = error_
	f.require(forbiddenErrorBodyFieldError)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBody) SetStatusCode(statusCode *int) {
	f.StatusCode = statusCode
	f.require(forbiddenErrorBodyFieldStatusCode)
}

func (f *ForbiddenErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler ForbiddenErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = ForbiddenErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *ForbiddenErrorBody) MarshalJSON() ([]byte, error) {
	type embed ForbiddenErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *ForbiddenErrorBody) String() string {
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	forbiddenErrorBodyOneFieldStatusCode   = big.NewInt(1 << 0)
	forbiddenErrorBodyOneFieldError        = big.NewInt(1 << 1)
	forbiddenErrorBodyOneFieldMessage      = big.NewInt(1 << 2)
	forbiddenErrorBodyOneFieldRequiredTier = big.NewInt(1 << 3)
)

type ForbiddenErrorBodyOne struct {
	// HTTP status code
	StatusCode int `json:"statusCode" url:"statusCode"`
	// Error type
	Error string `json:"error" url:"error"`
	// Error message explaining admin scope restriction
	Message string `json:"message" url:"message"`
	// Required tier for admin scope
	RequiredTier ForbiddenErrorBodyOneRequiredTier `json:"requiredTier" url:"requiredTier"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *ForbiddenErrorBodyOne) GetStatusCode() int {
	if f == nil {
		return 0
	}
	return f.StatusCode
}

func (f *ForbiddenErrorBodyOne) GetError() string {
	if f == nil {
		return ""
	}
	return f.Error
}

func (f *ForbiddenErrorBodyOne) GetMessage() string {
	if f == nil {
		return ""
	}
	return f.Message
}

func (f *ForbiddenErrorBodyOne) GetRequiredTier() ForbiddenErrorBodyOneRequiredTier {
	if f == nil {
		return ""
	}
	return f.RequiredTier
}

func (f *ForbiddenErrorBodyOne) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *ForbiddenErrorBodyOne) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBodyOne) SetStatusCode(statusCode int) {
	f.StatusCode = statusCode
	f.require(forbiddenErrorBodyOneFieldStatusCode)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBodyOne) SetError(error_ string) {
	f.Error = error_
	f.require(forbiddenErrorBodyOneFieldError)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBodyOne) SetMessage(message string) {
	f.Message = message
	f.require(forbiddenErrorBodyOneFieldMessage)
}

// SetRequiredTier sets the RequiredTier field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBodyOne) SetRequiredTier(requiredTier ForbiddenErrorBodyOneRequiredTier) {
	f.RequiredTier = requiredTier
	f.require(forbiddenErrorBodyOneFieldRequiredTier)
}

func (f *ForbiddenErrorBodyOne) UnmarshalJSON(data []byte) error {
	type unmarshaler ForbiddenErrorBodyOne
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = ForbiddenErrorBodyOne(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *ForbiddenErrorBodyOne) MarshalJSON() ([]byte, error) {
	type embed ForbiddenErrorBodyOne
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *ForbiddenErrorBodyOne) String() string {
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Required tier for admin scope
type ForbiddenErrorBodyOneRequiredTier string

const (
	ForbiddenErrorBodyOneRequiredTierEnterprise ForbiddenErrorBodyOneRequiredTier = "enterprise"
)

func NewForbiddenErrorBodyOneRequiredTierFromString(s string) (ForbiddenErrorBodyOneRequiredTier, error) {
	switch s {
	case "enterprise":
		return ForbiddenErrorBodyOneRequiredTierEnterprise, nil
	}
	var t ForbiddenErrorBodyOneRequiredTier
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (f ForbiddenErrorBodyOneRequiredTier) Ptr() *ForbiddenErrorBodyOneRequiredTier {
	return &f
}

// Required subscription tier
type ForbiddenErrorBodyRequiredTier string

const (
	ForbiddenErrorBodyRequiredTierPro        ForbiddenErrorBodyRequiredTier = "pro"
	ForbiddenErrorBodyRequiredTierEnterprise ForbiddenErrorBodyRequiredTier = "enterprise"
)

func NewForbiddenErrorBodyRequiredTierFromString(s string) (ForbiddenErrorBodyRequiredTier, error) {
	switch s {
	case "pro":
		return ForbiddenErrorBodyRequiredTierPro, nil
	case "enterprise":
		return ForbiddenErrorBodyRequiredTierEnterprise, nil
	}
	var t ForbiddenErrorBodyRequiredTier
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (f ForbiddenErrorBodyRequiredTier) Ptr() *ForbiddenErrorBodyRequiredTier {
	return &f
}

var (
	forbiddenErrorBodyZeroFieldStatusCode   = big.NewInt(1 << 0)
	forbiddenErrorBodyZeroFieldError        = big.NewInt(1 << 1)
	forbiddenErrorBodyZeroFieldMessage      = big.NewInt(1 << 2)
	forbiddenErrorBodyZeroFieldRequiredTier = big.NewInt(1 << 3)
)

type ForbiddenErrorBodyZero struct {
	// HTTP status code
	StatusCode int `json:"statusCode" url:"statusCode"`
	// Error type
	Error string `json:"error" url:"error"`
	// Error message explaining the tier requirement
	Message string `json:"message" url:"message"`
	// Required subscription tier
	RequiredTier *ForbiddenErrorBodyZeroRequiredTier `json:"requiredTier,omitempty" url:"requiredTier,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *ForbiddenErrorBodyZero) GetStatusCode() int {
	if f == nil {
		return 0
	}
	return f.StatusCode
}

func (f *ForbiddenErrorBodyZero) GetError() string {
	if f == nil {
		return ""
	}
	return f.Error
}

func (f *ForbiddenErrorBodyZero) GetMessage() string {
	if f == nil {
		return ""
	}
	return f.Message
}

func (f *ForbiddenErrorBodyZero) GetRequiredTier() *ForbiddenErrorBodyZeroRequiredTier {
	if f == nil {
		return nil
	}
	return f.RequiredTier
}

func (f *ForbiddenErrorBodyZero) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *ForbiddenErrorBodyZero) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBodyZero) SetStatusCode(statusCode int) {
	f.StatusCode = statusCode
	f.require(forbiddenErrorBodyZeroFieldStatusCode)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBodyZero) SetError(error_ string) {
	f.Error = error_
	f.require(forbiddenErrorBodyZeroFieldError)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBodyZero) SetMessage(message string) {
	f.Message = message
	f.require(forbiddenErrorBodyZeroFieldMessage)
}

// SetRequiredTier sets the RequiredTier field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForbiddenErrorBodyZero) SetRequiredTier(requiredTier *ForbiddenErrorBodyZeroRequiredTier) {
	f.RequiredTier = requiredTier
	f.require(forbiddenErrorBodyZeroFieldRequiredTier)
}

func (f *ForbiddenErrorBodyZero) UnmarshalJSON(data []byte) error {
	type unmarshaler ForbiddenErrorBodyZero
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = ForbiddenErrorBodyZero(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *ForbiddenErrorBodyZero) MarshalJSON() ([]byte, error) {
	type embed ForbiddenErrorBodyZero
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *ForbiddenErrorBodyZero) String() string {
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Required subscription tier
type ForbiddenErrorBodyZeroRequiredTier string

const (
	ForbiddenErrorBodyZeroRequiredTierPro        ForbiddenErrorBodyZeroRequiredTier = "pro"
	ForbiddenErrorBodyZeroRequiredTierEnterprise ForbiddenErrorBodyZeroRequiredTier = "enterprise"
)

func NewForbiddenErrorBodyZeroRequiredTierFromString(s string) (ForbiddenErrorBodyZeroRequiredTier, error) {
	switch s {
	case "pro":
		return ForbiddenErrorBodyZeroRequiredTierPro, nil
	case "enterprise":
		return ForbiddenErrorBodyZeroRequiredTierEnterprise, nil
	}
	var t ForbiddenErrorBodyZeroRequiredTier
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (f ForbiddenErrorBodyZeroRequiredTier) Ptr() *ForbiddenErrorBodyZeroRequiredTier {
	return &f
}

// Link expired or max uses reached
var (
	goneErrorBodyFieldStatusCode = big.NewInt(1 << 0)
	goneErrorBodyFieldError      = big.NewInt(1 << 1)
	goneErrorBodyFieldMessage    = big.NewInt(1 << 2)
	goneErrorBodyFieldRequestID  = big.NewInt(1 << 3)
)

type GoneErrorBody struct {
	StatusCode int     `json:"statusCode" url:"statusCode"`
	Error      string  `json:"error" url:"error"`
	Message    string  `json:"message" url:"message"`
	RequestID  *string `json:"requestId,omitempty" url:"requestId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GoneErrorBody) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GoneErrorBody) GetError() string {
	if g == nil {
		return ""
	}
	return g.Error
}

func (g *GoneErrorBody) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GoneErrorBody) GetRequestID() *string {
	if g == nil {
		return nil
	}
	return g.RequestID
}

func (g *GoneErrorBody) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GoneErrorBody) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GoneErrorBody) SetStatusCode(statusCode int) {
	g.StatusCode = statusCode
	g.require(goneErrorBodyFieldStatusCode)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GoneErrorBody) SetError(error_ string) {
	g.Error = error_
	g.require(goneErrorBodyFieldError)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GoneErrorBody) SetMessage(message string) {
	g.Message = message
	g.require(goneErrorBodyFieldMessage)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GoneErrorBody) SetRequestID(requestID *string) {
	g.RequestID = requestID
	g.require(goneErrorBodyFieldRequestID)
}

func (g *GoneErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler GoneErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GoneErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GoneErrorBody) MarshalJSON() ([]byte, error) {
	type embed GoneErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GoneErrorBody) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Server error
var (
	internalServerErrorBodyFieldError      = big.NewInt(1 << 0)
	internalServerErrorBodyFieldStatusCode = big.NewInt(1 << 1)
)

type InternalServerErrorBody struct {
	Error      *string `json:"error,omitempty" url:"error,omitempty"`
	StatusCode *int    `json:"statusCode,omitempty" url:"statusCode,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InternalServerErrorBody) GetError() *string {
	if i == nil {
		return nil
	}
	return i.Error
}

func (i *InternalServerErrorBody) GetStatusCode() *int {
	if i == nil {
		return nil
	}
	return i.StatusCode
}

func (i *InternalServerErrorBody) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InternalServerErrorBody) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalServerErrorBody) SetError(error_ *string) {
	i.Error = error_
	i.require(internalServerErrorBodyFieldError)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InternalServerErrorBody) SetStatusCode(statusCode *int) {
	i.StatusCode = statusCode
	i.require(internalServerErrorBodyFieldStatusCode)
}

func (i *InternalServerErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler InternalServerErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InternalServerErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InternalServerErrorBody) MarshalJSON() ([]byte, error) {
	type embed InternalServerErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InternalServerErrorBody) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Not found
var (
	notFoundErrorBodyFieldError      = big.NewInt(1 << 0)
	notFoundErrorBodyFieldStatusCode = big.NewInt(1 << 1)
)

type NotFoundErrorBody struct {
	Error      *string `json:"error,omitempty" url:"error,omitempty"`
	StatusCode *int    `json:"statusCode,omitempty" url:"statusCode,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NotFoundErrorBody) GetError() *string {
	if n == nil {
		return nil
	}
	return n.Error
}

func (n *NotFoundErrorBody) GetStatusCode() *int {
	if n == nil {
		return nil
	}
	return n.StatusCode
}

func (n *NotFoundErrorBody) GetExtraProperties() map[string]interface{} {
	return n.extraProperties
}

func (n *NotFoundErrorBody) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotFoundErrorBody) SetError(error_ *string) {
	n.Error = error_
	n.require(notFoundErrorBodyFieldError)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotFoundErrorBody) SetStatusCode(statusCode *int) {
	n.StatusCode = statusCode
	n.require(notFoundErrorBodyFieldStatusCode)
}

func (n *NotFoundErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler NotFoundErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NotFoundErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NotFoundErrorBody) MarshalJSON() ([]byte, error) {
	type embed NotFoundErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NotFoundErrorBody) String() string {
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Rate limited
var (
	tooManyRequestsErrorBodyFieldStatusCode = big.NewInt(1 << 0)
	tooManyRequestsErrorBodyFieldError      = big.NewInt(1 << 1)
	tooManyRequestsErrorBodyFieldMessage    = big.NewInt(1 << 2)
	tooManyRequestsErrorBodyFieldRetryAfter = big.NewInt(1 << 3)
)

type TooManyRequestsErrorBody struct {
	StatusCode int    `json:"statusCode" url:"statusCode"`
	Error      string `json:"error" url:"error"`
	Message    string `json:"message" url:"message"`
	RetryAfter *int   `json:"retryAfter,omitempty" url:"retryAfter,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TooManyRequestsErrorBody) GetStatusCode() int {
	if t == nil {
		return 0
	}
	return t.StatusCode
}

func (t *TooManyRequestsErrorBody) GetError() string {
	if t == nil {
		return ""
	}
	return t.Error
}

func (t *TooManyRequestsErrorBody) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

func (t *TooManyRequestsErrorBody) GetRetryAfter() *int {
	if t == nil {
		return nil
	}
	return t.RetryAfter
}

func (t *TooManyRequestsErrorBody) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TooManyRequestsErrorBody) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TooManyRequestsErrorBody) SetStatusCode(statusCode int) {
	t.StatusCode = statusCode
	t.require(tooManyRequestsErrorBodyFieldStatusCode)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TooManyRequestsErrorBody) SetError(error_ string) {
	t.Error = error_
	t.require(tooManyRequestsErrorBodyFieldError)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TooManyRequestsErrorBody) SetMessage(message string) {
	t.Message = message
	t.require(tooManyRequestsErrorBodyFieldMessage)
}

// SetRetryAfter sets the RetryAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TooManyRequestsErrorBody) SetRetryAfter(retryAfter *int) {
	t.RetryAfter = retryAfter
	t.require(tooManyRequestsErrorBodyFieldRetryAfter)
}

func (t *TooManyRequestsErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler TooManyRequestsErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TooManyRequestsErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TooManyRequestsErrorBody) MarshalJSON() ([]byte, error) {
	type embed TooManyRequestsErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TooManyRequestsErrorBody) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tooManyRequestsErrorBodyRateLimitFieldLimit     = big.NewInt(1 << 0)
	tooManyRequestsErrorBodyRateLimitFieldRemaining = big.NewInt(1 << 1)
	tooManyRequestsErrorBodyRateLimitFieldResetAt   = big.NewInt(1 << 2)
	tooManyRequestsErrorBodyRateLimitFieldWindow    = big.NewInt(1 << 3)
)

type TooManyRequestsErrorBodyRateLimit struct {
	// Maximum number of API keys that can be created per hour
	Limit int `json:"limit" url:"limit"`
	// Number of API keys that can still be created in the current window
	Remaining int `json:"remaining" url:"remaining"`
	// When the rate limit window resets
	ResetAt time.Time `json:"resetAt" url:"resetAt"`
	// Duration of the rate limit window
	Window string `json:"window" url:"window"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TooManyRequestsErrorBodyRateLimit) GetLimit() int {
	if t == nil {
		return 0
	}
	return t.Limit
}

func (t *TooManyRequestsErrorBodyRateLimit) GetRemaining() int {
	if t == nil {
		return 0
	}
	return t.Remaining
}

func (t *TooManyRequestsErrorBodyRateLimit) GetResetAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.ResetAt
}

func (t *TooManyRequestsErrorBodyRateLimit) GetWindow() string {
	if t == nil {
		return ""
	}
	return t.Window
}

func (t *TooManyRequestsErrorBodyRateLimit) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TooManyRequestsErrorBodyRateLimit) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TooManyRequestsErrorBodyRateLimit) SetLimit(limit int) {
	t.Limit = limit
	t.require(tooManyRequestsErrorBodyRateLimitFieldLimit)
}

// SetRemaining sets the Remaining field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TooManyRequestsErrorBodyRateLimit) SetRemaining(remaining int) {
	t.Remaining = remaining
	t.require(tooManyRequestsErrorBodyRateLimitFieldRemaining)
}

// SetResetAt sets the ResetAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TooManyRequestsErrorBodyRateLimit) SetResetAt(resetAt time.Time) {
	t.ResetAt = resetAt
	t.require(tooManyRequestsErrorBodyRateLimitFieldResetAt)
}

// SetWindow sets the Window field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TooManyRequestsErrorBodyRateLimit) SetWindow(window string) {
	t.Window = window
	t.require(tooManyRequestsErrorBodyRateLimitFieldWindow)
}

func (t *TooManyRequestsErrorBodyRateLimit) UnmarshalJSON(data []byte) error {
	type embed TooManyRequestsErrorBodyRateLimit
	var unmarshaler = struct {
		embed
		ResetAt *internal.DateTime `json:"resetAt"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TooManyRequestsErrorBodyRateLimit(unmarshaler.embed)
	t.ResetAt = unmarshaler.ResetAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TooManyRequestsErrorBodyRateLimit) MarshalJSON() ([]byte, error) {
	type embed TooManyRequestsErrorBodyRateLimit
	var marshaler = struct {
		embed
		ResetAt *internal.DateTime `json:"resetAt"`
	}{
		embed:   embed(*t),
		ResetAt: internal.NewDateTime(t.ResetAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TooManyRequestsErrorBodyRateLimit) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Unauthorized
var (
	unauthorizedErrorBodyFieldStatusCode = big.NewInt(1 << 0)
	unauthorizedErrorBodyFieldError      = big.NewInt(1 << 1)
	unauthorizedErrorBodyFieldMessage    = big.NewInt(1 << 2)
	unauthorizedErrorBodyFieldRequestID  = big.NewInt(1 << 3)
)

type UnauthorizedErrorBody struct {
	StatusCode int     `json:"statusCode" url:"statusCode"`
	Error      string  `json:"error" url:"error"`
	Message    string  `json:"message" url:"message"`
	RequestID  *string `json:"requestId,omitempty" url:"requestId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnauthorizedErrorBody) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UnauthorizedErrorBody) GetError() string {
	if u == nil {
		return ""
	}
	return u.Error
}

func (u *UnauthorizedErrorBody) GetMessage() string {
	if u == nil {
		return ""
	}
	return u.Message
}

func (u *UnauthorizedErrorBody) GetRequestID() *string {
	if u == nil {
		return nil
	}
	return u.RequestID
}

func (u *UnauthorizedErrorBody) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UnauthorizedErrorBody) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnauthorizedErrorBody) SetStatusCode(statusCode int) {
	u.StatusCode = statusCode
	u.require(unauthorizedErrorBodyFieldStatusCode)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnauthorizedErrorBody) SetError(error_ string) {
	u.Error = error_
	u.require(unauthorizedErrorBodyFieldError)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnauthorizedErrorBody) SetMessage(message string) {
	u.Message = message
	u.require(unauthorizedErrorBodyFieldMessage)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnauthorizedErrorBody) SetRequestID(requestID *string) {
	u.RequestID = requestID
	u.require(unauthorizedErrorBodyFieldRequestID)
}

func (u *UnauthorizedErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler UnauthorizedErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnauthorizedErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnauthorizedErrorBody) MarshalJSON() ([]byte, error) {
	type embed UnauthorizedErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnauthorizedErrorBody) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Resource not yet confirmed
var (
	unprocessableEntityErrorBodyFieldStatusCode = big.NewInt(1 << 0)
	unprocessableEntityErrorBodyFieldError      = big.NewInt(1 << 1)
	unprocessableEntityErrorBodyFieldMessage    = big.NewInt(1 << 2)
	unprocessableEntityErrorBodyFieldRequestID  = big.NewInt(1 << 3)
)

type UnprocessableEntityErrorBody struct {
	StatusCode int     `json:"statusCode" url:"statusCode"`
	Error      string  `json:"error" url:"error"`
	Message    string  `json:"message" url:"message"`
	RequestID  *string `json:"requestId,omitempty" url:"requestId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnprocessableEntityErrorBody) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UnprocessableEntityErrorBody) GetError() string {
	if u == nil {
		return ""
	}
	return u.Error
}

func (u *UnprocessableEntityErrorBody) GetMessage() string {
	if u == nil {
		return ""
	}
	return u.Message
}

func (u *UnprocessableEntityErrorBody) GetRequestID() *string {
	if u == nil {
		return nil
	}
	return u.RequestID
}

func (u *UnprocessableEntityErrorBody) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UnprocessableEntityErrorBody) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnprocessableEntityErrorBody) SetStatusCode(statusCode int) {
	u.StatusCode = statusCode
	u.require(unprocessableEntityErrorBodyFieldStatusCode)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnprocessableEntityErrorBody) SetError(error_ string) {
	u.Error = error_
	u.require(unprocessableEntityErrorBodyFieldError)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnprocessableEntityErrorBody) SetMessage(message string) {
	u.Message = message
	u.require(unprocessableEntityErrorBodyFieldMessage)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnprocessableEntityErrorBody) SetRequestID(requestID *string) {
	u.RequestID = requestID
	u.require(unprocessableEntityErrorBodyFieldRequestID)
}

func (u *UnprocessableEntityErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler UnprocessableEntityErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnprocessableEntityErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnprocessableEntityErrorBody) MarshalJSON() ([]byte, error) {
	type embed UnprocessableEntityErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnprocessableEntityErrorBody) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}
