// Code generated by Fern. DO NOT EDIT.

package marketplace_creator_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	promptvmgosdk "github.com/AIEngineering26/promptvm-go-sdk"
	client "github.com/AIEngineering26/promptvm-go-sdk/client"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestMarketplaceCreatorGetMyMarketplaceCreatorProfileWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.MarketplaceCreator.GetMyMarketplaceCreatorProfile(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarketplaceCreatorGetMyMarketplaceCreatorProfileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarketplaceCreatorGetMyMarketplaceCreatorProfileWithWireMock", "GET", "/api/v1/marketplace/creator/me", nil, 1)
}

func TestMarketplaceCreatorUpdateMyMarketplaceCreatorProfileWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.UpdateMyMarketplaceCreatorProfileRequest{}
	_, invocationErr := client.MarketplaceCreator.UpdateMyMarketplaceCreatorProfile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarketplaceCreatorUpdateMyMarketplaceCreatorProfileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarketplaceCreatorUpdateMyMarketplaceCreatorProfileWithWireMock", "PATCH", "/api/v1/marketplace/creator/me", nil, 1)
}

func TestMarketplaceCreatorCreateMarketplaceCreatorProfileWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.CreateMarketplaceCreatorProfileRequest{
		Bio: "bio",
	}
	_, invocationErr := client.MarketplaceCreator.CreateMarketplaceCreatorProfile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarketplaceCreatorCreateMarketplaceCreatorProfileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarketplaceCreatorCreateMarketplaceCreatorProfileWithWireMock", "POST", "/api/v1/marketplace/creator", nil, 1)
}

func TestMarketplaceCreatorGetMarketplaceCreatorProfileWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.GetMarketplaceCreatorProfileRequest{
		UserID: "userId",
	}
	_, invocationErr := client.MarketplaceCreator.GetMarketplaceCreatorProfile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarketplaceCreatorGetMarketplaceCreatorProfileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarketplaceCreatorGetMarketplaceCreatorProfileWithWireMock", "GET", "/api/v1/marketplace/creator/userId", nil, 1)
}
