// Code generated by Fern. DO NOT EDIT.

package settings_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	promptvmgosdk "github.com/AIEngineering26/promptvm-go-sdk"
	client "github.com/AIEngineering26/promptvm-go-sdk/client"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSettingsGetSettingsOverviewWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.GetSettingsOverviewRequest{
		OrgID: promptvmgosdk.String(
			"018e4a3b-0000-0000-0000-000000000001",
		),
	}
	_, invocationErr := client.Settings.GetSettingsOverview(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsGetSettingsOverviewWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsGetSettingsOverviewWithWireMock", "GET", "/api/v1/settings/overview", nil, 1)
}

func TestSettingsGetAdminTasksWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.GetAdminTasksRequest{
		OrgID: promptvmgosdk.String(
			"018e4a3b-0000-0000-0000-000000000001",
		),
	}
	_, invocationErr := client.Settings.GetAdminTasks(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsGetAdminTasksWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsGetAdminTasksWithWireMock", "GET", "/api/v1/settings/admin-tasks", nil, 1)
}

func TestSettingsListAuditLogsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.ListAuditLogsRequest{
		OrgID: promptvmgosdk.String(
			"018e4a3b-0000-0000-0000-000000000001",
		),
	}
	_, invocationErr := client.Settings.ListAuditLogs(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsListAuditLogsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsListAuditLogsWithWireMock", "GET", "/api/v1/audit-logs", nil, 1)
}

func TestSettingsListOrgTagsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.ListOrgTagsRequest{
		OrgID: promptvmgosdk.String(
			"018e4a3b-0000-0000-0000-000000000001",
		),
	}
	_, invocationErr := client.Settings.ListOrgTags(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsListOrgTagsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsListOrgTagsWithWireMock", "GET", "/api/v1/settings/tags", nil, 1)
}

func TestSettingsCreateOrgTagWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.CreateOrgTagRequest{
		OrgID: promptvmgosdk.String(
			"018e4a3b-0000-0000-0000-000000000001",
		),
		Name:      "name",
		Category:  promptvmgosdk.CreateOrgTagRequestCategoryEngineering,
		Protected: true,
	}
	_, invocationErr := client.Settings.CreateOrgTag(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsCreateOrgTagWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsCreateOrgTagWithWireMock", "POST", "/api/v1/settings/tags", nil, 1)
}

func TestSettingsDeleteOrgTagWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.DeleteOrgTagRequest{
		ID: "id",
		OrgID: promptvmgosdk.String(
			"018e4a3b-0000-0000-0000-000000000001",
		),
	}
	invocationErr := client.Settings.DeleteOrgTag(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsDeleteOrgTagWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsDeleteOrgTagWithWireMock", "DELETE", "/api/v1/settings/tags/id", nil, 1)
}

func TestSettingsUpdateOrgTagWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.UpdateOrgTagRequest{
		ID: "id",
		OrgID: promptvmgosdk.String(
			"018e4a3b-0000-0000-0000-000000000001",
		),
	}
	_, invocationErr := client.Settings.UpdateOrgTag(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsUpdateOrgTagWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsUpdateOrgTagWithWireMock", "PATCH", "/api/v1/settings/tags/id", nil, 1)
}

func TestSettingsGetSecurityStatusWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.GetSecurityStatusRequest{
		OrgID: promptvmgosdk.String(
			"018e4a3b-0000-0000-0000-000000000001",
		),
	}
	_, invocationErr := client.Settings.GetSecurityStatus(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsGetSecurityStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsGetSecurityStatusWithWireMock", "GET", "/api/v1/settings/security", nil, 1)
}

func TestSettingsSetupTotpWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Settings.SetupTotp(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsSetupTotpWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsSetupTotpWithWireMock", "POST", "/api/v1/settings/security/totp/setup", nil, 1)
}

func TestSettingsVerifyTotpWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.VerifyTotpRequest{
		Code: "code",
	}
	_, invocationErr := client.Settings.VerifyTotp(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsVerifyTotpWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsVerifyTotpWithWireMock", "POST", "/api/v1/settings/security/totp/verify", nil, 1)
}

func TestSettingsDisableTotpWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.DisableTotpRequest{
		Code: "code",
	}
	_, invocationErr := client.Settings.DisableTotp(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsDisableTotpWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsDisableTotpWithWireMock", "POST", "/api/v1/settings/security/totp/disable", nil, 1)
}

func TestSettingsRegenerateRecoveryCodesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.RegenerateRecoveryCodesRequest{
		Code: "code",
	}
	_, invocationErr := client.Settings.RegenerateRecoveryCodes(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsRegenerateRecoveryCodesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsRegenerateRecoveryCodesWithWireMock", "POST", "/api/v1/settings/security/recovery-codes/regenerate", nil, 1)
}

func TestSettingsChangePasswordWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.ChangePasswordRequest{
		CurrentPassword: "currentPassword",
		NewPassword:     "newPassword",
	}
	_, invocationErr := client.Settings.ChangePassword(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsChangePasswordWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsChangePasswordWithWireMock", "POST", "/api/v1/settings/security/password", nil, 1)
}

func TestSettingsUpdateOrgMfaPolicyWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.UpdateOrgMfaPolicyRequest{
		OrgID: promptvmgosdk.String(
			"018e4a3b-0000-0000-0000-000000000001",
		),
		RequireMfa: true,
	}
	_, invocationErr := client.Settings.UpdateOrgMfaPolicy(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsUpdateOrgMfaPolicyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsUpdateOrgMfaPolicyWithWireMock", "PUT", "/api/v1/settings/security/policy/mfa", nil, 1)
}

func TestSettingsSendEmailOtpWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Settings.SendEmailOtp(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsSendEmailOtpWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsSendEmailOtpWithWireMock", "POST", "/api/v1/settings/security/email-otp/send", nil, 1)
}

func TestSettingsVerifyEmailOtpWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.VerifyEmailOtpRequest{
		Code: "code",
	}
	_, invocationErr := client.Settings.VerifyEmailOtp(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsVerifyEmailOtpWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsVerifyEmailOtpWithWireMock", "POST", "/api/v1/settings/security/email-otp/verify", nil, 1)
}

func TestSettingsDisableEmailOtpWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.DisableEmailOtpRequest{
		Code: "code",
	}
	_, invocationErr := client.Settings.DisableEmailOtp(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSettingsDisableEmailOtpWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSettingsDisableEmailOtpWithWireMock", "POST", "/api/v1/settings/security/email-otp/disable", nil, 1)
}
