// Code generated by Fern. DO NOT EDIT.

package contexts

import (
	context "context"
	sdk "github.com/AIEngineering26/promptvm-go-sdk"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns the catalogue of supported content kinds (prompt, skill, ...) with their full KindDefinition. Stable shape — agents can build typed adapters from this response without consulting docs.
func (c *Client) ListContextKinds(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.ListContextKindsResponse, error) {
	response, err := c.WithRawResponse.ListContextKinds(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
