// Code generated by Fern. DO NOT EDIT.

package skills

import (
	context "context"
	promptvmgosdk "github.com/AIEngineering26/promptvm-go-sdk"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) ListSkills(
	ctx context.Context,
	request *promptvmgosdk.ListSkillsRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.ListSkillsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := baseURL + "/api/v1/skills"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *promptvmgosdk.ListSkillsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.ListSkillsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateSkill(
	ctx context.Context,
	request *promptvmgosdk.CreateSkillRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.CreateSkillResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := baseURL + "/api/v1/skills"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *promptvmgosdk.CreateSkillResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.CreateSkillResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetSkill(
	ctx context.Context,
	request *promptvmgosdk.GetSkillRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.GetSkillResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/skills/%v",
		request.SkillID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *promptvmgosdk.GetSkillResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.GetSkillResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteSkill(
	ctx context.Context,
	request *promptvmgosdk.DeleteSkillRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.DeleteSkillResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/skills/%v",
		request.SkillID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *promptvmgosdk.DeleteSkillResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.DeleteSkillResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateSkill(
	ctx context.Context,
	request *promptvmgosdk.UpdateSkillRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.UpdateSkillResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/skills/%v",
		request.SkillID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *promptvmgosdk.UpdateSkillResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.UpdateSkillResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
