// Code generated by Fern. DO NOT EDIT.

package promptdeployments

import (
	context "context"
	promptvmgosdk "github.com/AIEngineering26/promptvm-go-sdk"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Points the named environment at an existing published version. Idempotent — redeploying the same version updates deployedAt only.
func (c *Client) DeployPromptVersion(
	ctx context.Context,
	request *promptvmgosdk.DeployPromptVersionRequest,
	opts ...option.RequestOption,
) (*promptvmgosdk.DeployPromptVersionResponse, error) {
	response, err := c.WithRawResponse.DeployPromptVersion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
