// Code generated by Fern. DO NOT EDIT.

package hooks

import (
	context "context"
	promptvmgosdk "github.com/AIEngineering26/promptvm-go-sdk"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) ListHooks(
	ctx context.Context,
	request *promptvmgosdk.ListHooksRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.ListHooksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := baseURL + "/api/v1/hooks"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *promptvmgosdk.ListHooksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.ListHooksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateHook(
	ctx context.Context,
	request *promptvmgosdk.CreateHookRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.CreateHookResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := baseURL + "/api/v1/hooks"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *promptvmgosdk.CreateHookResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.CreateHookResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetHook(
	ctx context.Context,
	request *promptvmgosdk.GetHookRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.GetHookResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/hooks/%v",
		request.HookID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *promptvmgosdk.GetHookResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.GetHookResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteHook(
	ctx context.Context,
	request *promptvmgosdk.DeleteHookRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.DeleteHookResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/hooks/%v",
		request.HookID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *promptvmgosdk.DeleteHookResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.DeleteHookResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateHook(
	ctx context.Context,
	request *promptvmgosdk.UpdateHookRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.UpdateHookResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/hooks/%v",
		request.HookID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *promptvmgosdk.UpdateHookResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.UpdateHookResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ExportHook(
	ctx context.Context,
	request *promptvmgosdk.ExportHookRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.ExportHookResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/hooks/%v/export",
		request.HookID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *promptvmgosdk.ExportHookResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.ExportHookResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ValidateHook(
	ctx context.Context,
	request *promptvmgosdk.ValidateHookRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.ValidateHookResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := baseURL + "/api/v1/hooks/validate"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *promptvmgosdk.ValidateHookResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.ValidateHookResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ImportHooks(
	ctx context.Context,
	request *promptvmgosdk.ImportHooksRequest,
	opts ...option.RequestOption,
) (*core.Response[*promptvmgosdk.ImportHooksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"http://localhost:3000",
	)
	endpointURL := baseURL + "/api/v1/hooks/import"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *promptvmgosdk.ImportHooksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(promptvmgosdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*promptvmgosdk.ImportHooksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
