// Code generated by Fern. DO NOT EDIT.

package ai

import (
	context "context"
	sdk "github.com/AIEngineering26/promptvm-go-sdk"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Rewrites the submitted prompt to follow good prompting practices. Backed by the platform-internal AI middleware; the OpenRouter API key never leaves the backend. Accepts either JWT session or org-scoped pk:sk (write scope required for the pk:sk path).
func (c *Client) EnhancePrompt(
	ctx context.Context,
	request *sdk.EnhancePromptRequest,
	opts ...option.RequestOption,
) (*sdk.EnhancePromptResponse, error) {
	response, err := c.WithRawResponse.EnhancePrompt(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
