// Code generated by Fern. DO NOT EDIT.

package marketplacesocial

import (
	context "context"
	sdk "github.com/AIEngineering26/promptvm-go-sdk"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) FollowACreator(
	ctx context.Context,
	request *sdk.PostAPIV1MarketplaceCreatorCreatorUserIDFollowRequest,
	opts ...option.RequestOption,
) (*sdk.PostAPIV1MarketplaceCreatorCreatorUserIDFollowResponse, error) {
	response, err := c.WithRawResponse.FollowACreator(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UnfollowACreator(
	ctx context.Context,
	request *sdk.DeleteAPIV1MarketplaceCreatorCreatorUserIDFollowRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.UnfollowACreator(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) ListCreatorsIFollow(
	ctx context.Context,
	request *sdk.GetAPIV1MarketplaceCreatorMeFollowingRequest,
	opts ...option.RequestOption,
) (*sdk.GetAPIV1MarketplaceCreatorMeFollowingResponse, error) {
	response, err := c.WithRawResponse.ListCreatorsIFollow(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) FollowedCreatorListingFeed(
	ctx context.Context,
	request *sdk.GetAPIV1MarketplaceCreatorMeFeedRequest,
	opts ...option.RequestOption,
) (*sdk.GetAPIV1MarketplaceCreatorMeFeedResponse, error) {
	response, err := c.WithRawResponse.FollowedCreatorListingFeed(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListACreatorsFollowers(
	ctx context.Context,
	request *sdk.GetAPIV1MarketplaceCreatorCreatorUserIDFollowersRequest,
	opts ...option.RequestOption,
) (*sdk.GetAPIV1MarketplaceCreatorCreatorUserIDFollowersResponse, error) {
	response, err := c.WithRawResponse.ListACreatorsFollowers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
