// Code generated by Fern. DO NOT EDIT.

package marketplace_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	promptvmgosdk "github.com/AIEngineering26/promptvm-go-sdk"
	client "github.com/AIEngineering26/promptvm-go-sdk/client"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestMarketplaceAdminListContentTypesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Marketplace.AdminListContentTypes(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarketplaceAdminListContentTypesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarketplaceAdminListContentTypesWithWireMock", "GET", "/api/v1/admin/content-types", nil, 1)
}

func TestMarketplaceAdminCreateContentTypeWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.AdminCreateContentTypeRequest{
		Slug:        "slug",
		Label:       "label",
		PluralLabel: "pluralLabel",
		Icon:        "icon",
		Color:       "color",
	}
	_, invocationErr := client.Marketplace.AdminCreateContentType(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarketplaceAdminCreateContentTypeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarketplaceAdminCreateContentTypeWithWireMock", "POST", "/api/v1/admin/content-types", nil, 1)
}

func TestMarketplaceAdminReorderContentTypesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.AdminReorderContentTypesRequest{
		Items: []*promptvmgosdk.AdminReorderContentTypesRequestItemsItem{
			&promptvmgosdk.AdminReorderContentTypesRequestItemsItem{
				Slug:      "slug",
				SortOrder: 1,
			},
		},
	}
	_, invocationErr := client.Marketplace.AdminReorderContentTypes(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarketplaceAdminReorderContentTypesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarketplaceAdminReorderContentTypesWithWireMock", "PATCH", "/api/v1/admin/content-types/reorder", nil, 1)
}

func TestMarketplaceAdminDeleteContentTypeWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.AdminDeleteContentTypeRequest{
		Slug: "slug",
	}
	invocationErr := client.Marketplace.AdminDeleteContentType(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarketplaceAdminDeleteContentTypeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarketplaceAdminDeleteContentTypeWithWireMock", "DELETE", "/api/v1/admin/content-types/slug", nil, 1)
}

func TestMarketplaceAdminUpdateContentTypeWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &promptvmgosdk.AdminUpdateContentTypeRequest{
		Slug: "slug",
	}
	_, invocationErr := client.Marketplace.AdminUpdateContentType(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarketplaceAdminUpdateContentTypeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarketplaceAdminUpdateContentTypeWithWireMock", "PATCH", "/api/v1/admin/content-types/slug", nil, 1)
}
