// Code generated by Fern. DO NOT EDIT.

package users

import (
	context "context"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Soft-deletes the caller: every organization the user owns is deleted (workspaces and files soft-deleted, members removed, API keys and sessions revoked, Stripe subscription cancelled immediately), memberships in other organizations are removed, and all of the user's sessions and API keys are revoked. Irreversible from the client perspective; data is retained for 30 days for compliance before purge.
func (c *Client) DeleteAccount(
	ctx context.Context,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteAccount(
		ctx,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
