// Code generated by Fern. DO NOT EDIT.

package marketplacecreator

import (
	context "context"
	sdk "github.com/AIEngineering26/promptvm-go-sdk"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) GetMarketplaceCreatorProfile(
	ctx context.Context,
	request *sdk.GetMarketplaceCreatorProfileRequest,
	opts ...option.RequestOption,
) (*sdk.GetMarketplaceCreatorProfileResponse, error) {
	response, err := c.WithRawResponse.GetMarketplaceCreatorProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Resolves a cosmetic profile handle. Falls back to handles the creator previously held, in which case `meta.redirectTo` carries the current handle so the caller can issue a 301. Unrelated to `users.username`, which remains the install namespace for `creator/name` refs.
func (c *Client) GetMarketplaceCreatorProfileByHandle(
	ctx context.Context,
	request *sdk.GetMarketplaceCreatorProfileByHandleRequest,
	opts ...option.RequestOption,
) (*sdk.GetMarketplaceCreatorProfileByHandleResponse, error) {
	response, err := c.WithRawResponse.GetMarketplaceCreatorProfileByHandle(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CheckMarketplaceCreatorHandleAvailability(
	ctx context.Context,
	request *sdk.CheckMarketplaceCreatorHandleAvailabilityRequest,
	opts ...option.RequestOption,
) (*sdk.CheckMarketplaceCreatorHandleAvailabilityResponse, error) {
	response, err := c.WithRawResponse.CheckMarketplaceCreatorHandleAvailability(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) BrowseMarketplaceCreators(
	ctx context.Context,
	request *sdk.BrowseMarketplaceCreatorsRequest,
	opts ...option.RequestOption,
) (*sdk.BrowseMarketplaceCreatorsResponse, error) {
	response, err := c.WithRawResponse.BrowseMarketplaceCreators(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetMyMarketplaceCreatorProfile(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.GetMyMarketplaceCreatorProfileResponse, error) {
	response, err := c.WithRawResponse.GetMyMarketplaceCreatorProfile(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UpdateMyMarketplaceCreatorProfile(
	ctx context.Context,
	request *sdk.UpdateMyMarketplaceCreatorProfileRequest,
	opts ...option.RequestOption,
) (*sdk.UpdateMyMarketplaceCreatorProfileResponse, error) {
	response, err := c.WithRawResponse.UpdateMyMarketplaceCreatorProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateMarketplaceCreatorProfile(
	ctx context.Context,
	request *sdk.CreateMarketplaceCreatorProfileRequest,
	opts ...option.RequestOption,
) (*sdk.CreateMarketplaceCreatorProfileResponse, error) {
	response, err := c.WithRawResponse.CreateMarketplaceCreatorProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ClaimMarketplaceCreatorProfile(
	ctx context.Context,
	request *sdk.ClaimMarketplaceCreatorProfileRequest,
	opts ...option.RequestOption,
) (*sdk.ClaimMarketplaceCreatorProfileResponse, error) {
	response, err := c.WithRawResponse.ClaimMarketplaceCreatorProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
