// Code generated by Fern. DO NOT EDIT.

package marketplacecreator

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) GetMyMarketplaceCreatorProfile(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.GetMyMarketplaceCreatorProfileResponse, error) {
	response, err := c.WithRawResponse.GetMyMarketplaceCreatorProfile(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UpdateMyMarketplaceCreatorProfile(
	ctx context.Context,
	request *sdk.UpdateMyMarketplaceCreatorProfileRequest,
	opts ...option.RequestOption,
) (*sdk.UpdateMyMarketplaceCreatorProfileResponse, error) {
	response, err := c.WithRawResponse.UpdateMyMarketplaceCreatorProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateMarketplaceCreatorProfile(
	ctx context.Context,
	request *sdk.CreateMarketplaceCreatorProfileRequest,
	opts ...option.RequestOption,
) (*sdk.CreateMarketplaceCreatorProfileResponse, error) {
	response, err := c.WithRawResponse.CreateMarketplaceCreatorProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetMarketplaceCreatorProfile(
	ctx context.Context,
	request *sdk.GetMarketplaceCreatorProfileRequest,
	opts ...option.RequestOption,
) (*sdk.GetMarketplaceCreatorProfileResponse, error) {
	response, err := c.WithRawResponse.GetMarketplaceCreatorProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
