// Code generated by Fern. DO NOT EDIT.

package cliauth

import (
	context "context"
	promptvmgosdk "github.com/AIEngineering26/promptvm-go-sdk"
	core "github.com/AIEngineering26/promptvm-go-sdk/core"
	internal "github.com/AIEngineering26/promptvm-go-sdk/internal"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Called by the frontend consent page after the user authorizes a CLI login request. Returns a one-time authorization code tied to the PKCE challenge.
func (c *Client) CliAuthorize(
	ctx context.Context,
	request *promptvmgosdk.CliAuthorizeRequest,
	opts ...option.RequestOption,
) (*promptvmgosdk.CliAuthorizeResponse, error) {
	response, err := c.WithRawResponse.CliAuthorize(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CliDeviceAuthorize(
	ctx context.Context,
	request *promptvmgosdk.CliDeviceAuthorizeRequest,
	opts ...option.RequestOption,
) (*promptvmgosdk.CliDeviceAuthorizeResponse, error) {
	response, err := c.WithRawResponse.CliDeviceAuthorize(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListCliSessions(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*promptvmgosdk.ListCliSessionsResponseItem, error) {
	response, err := c.WithRawResponse.ListCliSessions(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) RevokeCliSession(
	ctx context.Context,
	request *promptvmgosdk.RevokeCliSessionRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.RevokeCliSession(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// OAuth 2.0 token endpoint supporting grant_type=authorization_code (with PKCE) and grant_type=refresh_token. Public — no client secret.
func (c *Client) CliTokenExchange(
	ctx context.Context,
	request *promptvmgosdk.CliTokenExchangeRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.CliTokenExchange(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CliDeviceCode(
	ctx context.Context,
	request *promptvmgosdk.CliDeviceCodeRequest,
	opts ...option.RequestOption,
) (*promptvmgosdk.CliDeviceCodeResponse, error) {
	response, err := c.WithRawResponse.CliDeviceCode(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CliDeviceToken(
	ctx context.Context,
	request *promptvmgosdk.CliDeviceTokenRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.CliDeviceToken(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
