// Code generated by Fern. DO NOT EDIT.

package templates_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	sdk "github.com/AIEngineering26/promptvm-go-sdk"
	client "github.com/AIEngineering26/promptvm-go-sdk/client"
	option "github.com/AIEngineering26/promptvm-go-sdk/option"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestTemplatesConvertPromptToTemplateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.ConvertPromptToTemplateRequest{
		PromptID: "promptId",
	}
	_, invocationErr := client.Templates.ConvertPromptToTemplate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTemplatesConvertPromptToTemplateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTemplatesConvertPromptToTemplateWithWireMock", "POST", "/api/v1/prompts/promptId/convert-to-template", nil, 1)
}

func TestTemplatesListTemplatesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.ListTemplatesRequest{
		WorkspaceID: "workspaceId",
	}
	_, invocationErr := client.Templates.ListTemplates(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTemplatesListTemplatesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTemplatesListTemplatesWithWireMock", "GET", "/api/v1/templates", map[string]string{"workspaceId": "workspaceId"}, 1)
}

func TestTemplatesCreatePromptFromTemplateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.CreatePromptFromTemplateRequest{
		TemplateID:  "templateId",
		Name:        "name",
		WorkspaceID: "workspaceId",
	}
	_, invocationErr := client.Templates.CreatePromptFromTemplate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTemplatesCreatePromptFromTemplateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTemplatesCreatePromptFromTemplateWithWireMock", "POST", "/api/v1/prompts/from-template", nil, 1)
}
